In [1]:
import os
import h5py
import numpy as np
from IPython.lib.deepreload import reload
import matplotlib.pyplot as plt
from collections import OrderedDict
import skimage.io as io
%matplotlib qt

In [2]:
import xrdmaptools
from xrdmaptools.XRDMap import XRDMap
from xrdmaptools.reflections.SpotModels import GaussianFunctions
reload(xrdmaptools);

c:\Users\emusterma\AppData\Local\anaconda3\envs\sXRDMap-py311-1.0\Lib\site-packages\pyopencl\cache.py:495: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  _create_built_program_from_source_cached(


Connecting to databrokers...failed.


In [3]:
from xrdmaptools.utilities.math import wavelength_2_energy

wavelength_2_energy(0.82656)

15.000024007113856

In [4]:
scanid = 107243

filedir = 'D:\\Musterman_postdoc\\Varun_data\\'
map_filename = f'scan{scanid}_xrd.tiff'

test1 = XRDMap.from_image_stack(map_filename, wd=filedir, energy=15, scanid=scanid, save_hdf=False)

scanid = 107253

filedir = 'D:\\Musterman_postdoc\\Varun_data\\'
map_filename = f'scan{scanid}_xrd.tiff'

test2 = XRDMap.from_image_stack(map_filename, wd=filedir, energy=15, scanid=scanid, save_hdf=False)

scanid = 107263

filedir = 'D:\\Musterman_postdoc\\Varun_data\\'
map_filename = f'scan{scanid}_xrd.tiff'

test3 = XRDMap.from_image_stack(map_filename, wd=filedir, energy=15, scanid=scanid, save_hdf=False)

Loading images...done!
Assumed map shape is (41, 41) with images of (972, 1536)
Loading images...done!
Assumed map shape is (41, 41) with images of (972, 1536)
Loading images...done!
Assumed map shape is (41, 41) with images of (972, 1536)


In [36]:
scanid = 107263

filedir = 'D:\\Musterman_postdoc\\Varun_data\\'
map_filename = f'scan{scanid}_xrd.tiff'

test3 = XRDMap.from_image_stack(map_filename, wd=filedir, energy=15, scanid=scanid, save_hdf=False)

Loading images...done!
Assumed map shape is (41, 41) with images of (972, 1536)


In [14]:
test3.map.med_image;

In [17]:
test3.map.dtype = np.float32

In [18]:
test3.map.dtype = np.float32

test3.map.images -= test3.map.med_image

In [23]:
np.unravel_index(1576, test3.map.map_shape)

(38, 18)

In [24]:
test3.plot_image([38, 18])

In [29]:
test2.plot_interactive_map(display_map=np.sum(test2.map.images[:, :, 300:360, 700:770], axis=(2, 3)),
                            img_vmin=1e3, img_vmax=2e3)

In [34]:
test3.plot_interactive_map(display_map=np.sum(test3.map.images[:, :, 300:360, 700:770], axis=(2, 3)),
                            img_vmin=-3.5e3, img_vmax=-2e3)

In [5]:
test1.map.med_image
test2.map.med_image
test3.map.med_image;

In [11]:
test3.map.images -= test3.map.med_image

In [11]:
test.plot_interactive_map(display_map=test.map.max_map, img_vmin=0, img_vmax=1e4)

In [14]:
np.unravel_index(np.argmax(test.map.images[22, 28]), test.map.image_shape)

(329, 736)

In [10]:
test3.plot_image(test3.map.images[22, 28, 300:360, 700:770])

In [27]:
np.sum(test.map.images[:, :, 300:360, 700:770], axis=(2, 3))

array([[6367417, 6283277, 6288827, ..., 6293338, 6293140, 6278595],
       [6299926, 6294414, 6278905, ..., 6299546, 6302492, 6292883],
       [6367375, 6279981, 6298709, ..., 6295937, 6287933, 6297607],
       ...,
       [6361121, 6295429, 6286304, ..., 6313112, 6312292, 6317346],
       [6323595, 6323322, 6289798, ..., 6290436, 6324042, 6305934],
       [6366079, 6297589, 6307345, ..., 6308725, 6321375, 6327826]],
      dtype=uint32)

In [17]:
test1.plot_interactive_map(img_vmin=0, img_vmax=1e4)

In [12]:
test3.plot_interactive_map(display_map=np.sum(test3.map.images[:, :, 300:360, 700:770], axis=(2, 3)),
                            img_vmin=0, img_vmax=1e4)

In [ ]:
from xrdmaptools.plot.interactive_plotting import interactive_dynamic_2d_plot


interactive_dynamic_2d_plot(np.asarray(test.map.images), tth=None, chi=None,
                                    display_map=display_map,
                                    **kwargs)

In [37]:
import skimage.io as io

#test1.map.images = io.imread()
# 4D image (map_x, map_y, img_y, img_x)
# test1.map.images = test1.map.images.reshape(41, 41, img_y, img_x)

fig, ax = plt.subplots(1, 3, figsize=(8, 3), dpi=200)

vmin=6.3e6
vmax=1.2e7

im = ax[0].imshow(np.sum(test1.map.images[:, :, 300:360, 700:770], axis=(2, 3)), vmin=vmin, vmax=vmax)
fig.colorbar(im,  ax=ax[0], shrink=0.5)
ax[0].set_title('scan107243')

im = ax[1].imshow(np.sum(test2.map.images[:, :, 300:360, 700:770], axis=(2, 3)), vmin=vmin, vmax=vmax)
fig.colorbar(im,  ax=ax[1], shrink=0.5)
ax[1].set_title('scan107253')

im = ax[2].imshow(np.sum(test3.map.images[:, :, 300:360, 700:770], axis=(2, 3)), vmin=vmin, vmax=vmax)
fig.colorbar(im,  ax=ax[2], shrink=0.5)
ax[2].set_title('scan107263')

fig.show()

In [3]:
scanid = 153076
scanid = 153273
scanid = 153126
#scanid = 153248
#scanid = 153485
filedir = 'D:\\Musterman_postdoc\\20240223_Musterman\\testing_maps\\'
#filedir = 'D:\\Musterman_postdoc\\20240223_Musterman\\xrd_maps\\'
h5_filename = f'scan{scanid}_xrd.h5'
test = XRDMap.from_hdf(h5_filename, wd=filedir, save_hdf=False, dask_enabled=False)

Loading data from hdf file...
Loading most recent images (final_images)...done!
Loading reciprocal positions...done!
Loading saved phases...done!
Loading scalers...done!
Loading positions...done!
Loading reflection spots...done!
Instantiating ImageMap...done!
XRD Map loaded!


In [4]:
filedir = 'D:\\Musterman_postdoc\\20240223_Musterman\\calibrations\\'

#test.set_calibration('scan153043_dexela_calibration.poni', filedir=filedir)
test.set_calibration('new\\scan153043_dexela_calibration.poni', filedir=filedir)

Calibration performed under different settings. Adjusting calibration.


In [5]:
test._del_arr()

In [4]:
dark_id = 153074
#dark_id = 153086
#dark_id = 153247
#dark_id = 153247
#dark_id = 153481
dark_dir = 'D:\\Musterman_postdoc\\20240223_Musterman\\dark_fields\\'
dir_mask = [str(dark_id) in d for d in os.listdir(dark_dir)]

dark_field = io.imread(f'{dark_dir}{np.array(os.listdir(dark_dir))[dir_mask][0]}').astype(np.float32)
test.map.correct_dark_field(dark_field=dark_field)

Correcting dark-field...done!


In [5]:
#test.map.correct_outliers()
test.map.normalize_scaler()

Normalize image by i0 scaler...done!


In [6]:
test.map.apply_lorentz_correction(apply=False)
test.map.apply_polarization_correction()
test.map.apply_solidangle_correction()

Applying X-ray polarization correction...done!
Applying solid angle correction...done!


In [7]:
from xrdmaptools.utilities.utilities import delta_array
omega = 4 * np.arcsin(np.sin(np.radians(test.delta_tth / 2)) * np.sin(np.radians(test.delta_chi / 2)))

test.map.images /= (omega * np.sin(np.radians(test.tth_arr)))
test.map.corrections['lorentz'] = True

In [8]:
#test.map.estimate_background(method='bruckner', binning=2, min_prominence=1)
test.map.estimate_background(method='bruckner', binning=2, min_prominence=0.1)

Estimating background with Bruckner algorithm.


100%|██████████| 3321/3321 [01:24<00:00, 39.40it/s]


In [9]:
test.map.remove_background()

Removing background...done!


In [10]:
test.map.rescale_images(arr_min=0)
test.map.finalize_images()

Caution: Images not corrected for:
	absorption
	flat_field
	outliers
	pixel_defects
	pixel_distortions
	polar_calibration
Cleaning and updating image information...
Diffraction map size is 4.618 GB.
No hdf file specified. Images will not be saved.


In [11]:
test.find_spots(multiplier=3, expansion=10, radius=10, size=3, threshold_method='minimum')
test.fit_spots(GaussianFunctions, max_dist=0.2, sigma=1)
test.initial_spot_analysis()

Searching images for spots...


100%|██████████| 3321/3321 [00:50<00:00, 65.14it/s]


Estimating spot characteristics...


100%|██████████| 64438/64438 [04:52<00:00, 220.52it/s]


Scheduling blob segmentation for spot fits...


100%|██████████| 3321/3321 [01:02<00:00, 52.94it/s]


Segmenting blobs for spot fits...


100%|██████████| 3321/3321 [01:14<00:00, 44.35it/s]


Fitting spots in blobs...


100%|██████████| 51639/51639 [31:40<00:00, 27.18it/s]  


Successfully fit 62125 / 64438 spots ( 96.4 % ).
Extracting more information from peak parameters...


100%|██████████| 64438/64438 [01:06<00:00, 962.01it/s] 

Converting peaks positions to q-space...done!


In [282]:
test.plot_image()

In [38]:
cif_dir = '''C:\\Users\\emusterma\\OneDrive - Brookhaven National Laboratory\\Documents\\Postdoc\\Literature\\CIF\\'''
test.clear_phases()
test.load_phase('AMCSD\\Stibnite_0008636.cif', filedir=cif_dir, phase_name="stibnite")
test.load_phase('AMCSD\\Platinum_0011157.cif', filedir=cif_dir, phase_name="platinum")
test.load_phase('AMCSD\\Tungsten_0011236.cif', filedir=cif_dir, phase_name="tungsten_2")
test.load_phase('AMCSD\\Iron_0011146.cif', filedir=cif_dir, phase_name="304SS-austenite")
test.phases['304SS-austenite'].a = 3.529

In [510]:
test.plot_interactive_map(img_vmax=0.1, img_vmin=0)

In [273]:
from xrdmaptools.geometry.geometry import estimate_image_coords

def vector_angle(v1, v2, degrees=False):
    angle = np.arccos(np.dot(v1, v2) / (np.linalg.norm(v1, axis=-1) *  np.linalg.norm(v2, axis=-1)))
    if degrees:
        angle = np.degrees(angle)
    return angle

def q_2_polar(q_vect, wavelength=None, degrees=False):
    q_vect = np.asarray(q_vect)
    q_norm = np.linalg.norm(q_vect, axis=-1)

    # Find tth and chi
    theta = np.pi / 2 - vector_angle(q_vect, [0, 0, -1], degrees=False) # always false
    tth = 2 * theta
    # Negative qx to switch to pyFAI coordinate system
    chi = np.arctan2(q_vect[..., 1], -q_vect[..., 0])

    if degrees:
        tth = np.degrees(tth)
        chi = np.degrees(chi)

    # Get radius of Ewald sphere and wavelength
    if wavelength is None:
        r = 0.5 * q_norm / np.sin(theta)
        wavelength = 2 * np.pi / r

    return tth, chi, wavelength


# Find nearest q-space position on Ewald sphere within a certain threshold
def nearest_q_on_ewald(q_vect, wavelength, near_thresh=None):
    # Currently no way to bound within surface measured by detector
    
    q_vect = np.asarray(q_vect)

    r = 2 * np.pi / wavelength # radius of Ewald sphere
    qx = q_vect[..., 0] 
    qy = q_vect[..., 1]
    qz = q_vect[..., 2] + r # shift vector origin to center of Ewald sphere
    q_norm = np.linalg.norm([qx, qy, qz], axis=0) # evil things with axis ordering

    # Solving parametric equation of a vector intercepting the Ewald sphere
    t = r / q_norm

    # Nearest q_vect, with transmission center
    qx_near = t * qx
    qy_near = t * qy
    qz_near = t * qz - r

    # Distance normal to Ewald sphere
    # Positive means input is outside of Ewald sphere
    q_dist = q_norm - np.linalg.norm([qx_near, qy_near, qz_near + r], axis=0)

    # Mask out values too far away from Ewald sphere
    if near_thresh is not None:
        dist_mask = np.abs(q_dist) > near_thresh
        qx_near[dist_mask] = np.nan
        qy_near[dist_mask] = np.nan
        qz_near[dist_mask] = np.nan
        q_dist[dist_mask] = np.nan

    # Transpose necessary to maintain input shape. Maybe best to shift all q_vectors to be consistent
    return np.array([qx_near, qy_near, qz_near]).T, q_dist


def nearest_polar_on_ewald(q_vect, wavelength,
                          near_thresh=None, degrees=False):

    q_near, q_dist = nearest_q_on_ewald(q_vect,
                                        wavelength,
                                        near_thresh=near_thresh)
    
    tth, chi, wavelength = q_2_polar(q_near,
                                     wavelength=wavelength,
                                     degrees=degrees)
    
    return tth, chi


def nearest_pixels_on_ewald(q_vect, wavelength, tth_arr, chi_arr,
                            near_thresh=None, degrees=False, method='nearest'):
    # degrees bool must match tth_arr and chi_arr input values
    
    tth, chi = nearest_polar_on_ewald(q_vect,
                                      wavelength,
                                      near_thresh=near_thresh,
                                      degrees=degrees)
    
    if near_thresh is not None:
        nan_mask = np.any([np.isnan(tth), np.isnan(chi)], axis=0)
        tth = tth[~nan_mask]
        chi = chi[~nan_mask]

    est_img_coords = estimate_image_coords(np.array([tth, chi]).T, tth_arr, chi_arr, method)

    bound_mask = np.any([
        est_img_coords[:, 0] <= 0,
        est_img_coords[:, -1] <= 0,
        est_img_coords[:, 0] >= test.tth_arr.shape[1] - 1,
        est_img_coords[:, -1] >= test.tth_arr.shape[0] - 1
    ], axis=0)

    return est_img_coords[~bound_mask]

In [460]:
from xrdmaptools.crystal.Phase import generate_reciprocal_lattice

phase = test.phases['stibnite']

all_hkls, all_qs, all_fs = generate_reciprocal_lattice(phase, tth_range=(0, np.max(test.tth_arr)))

In [461]:
q_near, q_dist = nearest_q_on_ewald(all_qs, test.wavelength, near_thresh=None)

In [462]:
tth, chi = nearest_polar_on_ewald(all_qs, test.wavelength,
                            near_thresh=0.1, degrees=True)

In [464]:
img_coords = nearest_pixels_on_ewald(all_qs, test.wavelength, test.tth_arr, test.chi_arr,
                            near_thresh=0.05, degrees=True)

In [760]:
from xrdmaptools.crystal.orientation import euler_rotation

pixel_indices = [4, 12]

#r_qs = euler_rotation(all_qs, *euler_map[*pixel_indices])
#r_qs = all_qs @ g_func(*euler_map[*pixel_indices]).T
r_qs = all_qs @ g_func(*orientations[np.argmax(fit_list)])
#r_qs = all_qs @ orientation_map[*pixel_indices]

#r_qs = all_qs @ grain_list[0][-1]

img_coords = nearest_pixels_on_ewald(r_qs, test.wavelength, test.tth_arr, test.chi_arr,
                            near_thresh=0.25, degrees=True)

np.sum(test.map.images[*pixel_indices, *img_coords[:, ::-1].T])

8.112663

In [761]:
fig, ax = test.plot_image(pixel_indices, return_plot=True, vmin=0, vmax=0.1)

ax.scatter(*img_coords.T)

plt.show()

In [302]:
pixel_df = test.pixel_spots([pixel_indices])
spot_qs = pixel_df[['qx', 'qy', 'qz']].values
spot_ints = pixel_df[['guess_int']].values

spot_qs, spot_ints = combine_nearby_spots(spot_qs, spot_ints, max_dist=0.1, max_neighbors=np.inf)

In [307]:
img_coords = nearest_pixels_on_ewald(spot_qs, test.wavelength, test.tth_arr, test.chi_arr,
                            near_thresh=0.05, degrees=True)
img_coords

array([[1106,  172],
       [ 281,  847],
       [ 544,  276],
       [1412,  585],
       [1120,  244],
       [1323,  137],
       [ 248,  913],
       [ 554,  333],
       [ 854,  685],
       [ 224,  956],
       [ 908,  250],
       [1199,  655],
       [1375,  180],
       [1534,   51],
       [1333,  218],
       [1135,  379]])

In [449]:
from sklearn.metrics.pairwise import euclidean_distances

def iterative_indexing(spot_qs, Phase, tth_range, cut_off=0.9, start_angle=10, angle_resolution=0.001,
                                  euler_bounds=[[-180, 180], [0, 180], [-180, 180]]):
    from itertools import product

    #spot_qs = pixel_df[['qx', 'qy', 'qz']].values
    all_hkls, all_qs, all_fs = generate_reciprocal_lattice(Phase, tth_range=tth_range)

    dist = euclidean_distances(all_qs)
    min_q = np.min(dist[dist > 0])

    step = start_angle
    print(f'Finding orientations with {step} deg resolution...')
    phi1_list = np.arange(*euler_bounds[0], step)
    PHI_list = np.arange(*euler_bounds[1], step)
    phi2_list = np.arange(*euler_bounds[2], step)
    orientations = list(product(phi1_list, PHI_list, phi2_list))

    fit_ori = []
    fit_min = []
    ITERATE = True
    while ITERATE:
        step /= 2 # half the resolution each time
        if step <= angle_resolution:
            ITERATE = False

        print(f'Evaluating the current Euler space...')
        min_list = []
        for orientation in tqdm(orientations):
            img_coords = nearest_pixels_on_ewald(euler_rotation(all_qs, *orientation),
                                                 test.wavelength, test.tth_arr, test.chi_arr,
                            near_thresh=0.25, degrees=True)
            min_list.append(test.map.images[*pixel_indices, *img_coords[:, ::-1].T])
        
        fit_min.append(np.max(min_list))
        fit_ori.append(orientations[np.argmax(min_list)])
        
        min_mask = min_list > cut_off * (np.max(min_list) - np.min(min_list)) + np.min(min_list)
        best_orientations = np.asarray(orientations)[min_mask]

        print(f'Finding new orientations with {step:.4f} deg resolution...')
        new_orientations = []
        for orientation in best_orientations:
            phi1, PHI, phi2 = orientation
            new_phi1 = [phi1 - step, phi1, phi1 + step]
            new_PHI = [PHI - step, PHI, PHI + step]
            new_phi2 = [phi2 - step, phi2, phi2 + step]

            sub_orientations = product(new_phi1, new_PHI, new_phi2)

            for sub_orientation in sub_orientations:
                if sub_orientation not in new_orientations:
                    new_orientations.append(sub_orientation)
            
            orientations = new_orientations

    print(f'Evaluating the last Euler space...')
    min_list = []
    for orientation in orientations:
        img_coords = nearest_pixels_on_ewald(euler_rotation(all_qs, *orientation),
                                                test.wavelength, test.tth_arr, test.chi_arr,
                        near_thresh=0.25, degrees=True)
        min_list.append(test.map.images[*pixel_indices, *img_coords[:, ::-1].T])
    
    fit_min.append(np.max(min_list))
    fit_ori.append(orientations[np.argmax(min_list)])

    return fit_ori, fit_min

In [734]:
from itertools import product
from tqdm import tqdm

step = 5
print(f'Finding orientations with {step} deg resolution...')
phi1_list = np.arange(0, 180, step)
PHI_list = np.arange(0, 90, step)
phi2_list = np.arange(0, 180, step)
orientations = list(product(phi1_list, PHI_list, phi2_list))

tth_list, chi_list = [], []
tth_all, chi_all = [], []
for orientation in tqdm(orientations):
    tth, chi = nearest_polar_on_ewald(euler_rotation(all_qs, *orientation),
                                            test.wavelength, near_thresh=0.05,
                                            degrees=True)
    
    nan_mask = np.any([np.isnan(tth), np.isnan(chi)], axis=0)
    tth = tth[~nan_mask]
    chi = chi[~nan_mask]
    
    tth_list.append(tth)
    tth_all.extend(tth)
    chi_list.append(chi)
    chi_all.extend(chi)
    #min_list.append(np.sum(test.map.images[*pixel_indices, *img_coords[:, ::-1].T]))

img_coords = estimate_image_coords(np.array([tth_all, chi_all]).T, test.tth_arr, test.chi_arr)

bound_mask = np.any([
    img_coords[:, 0] <= 0,
    img_coords[:, -1] <= 0,
    img_coords[:, 0] >= test.tth_arr.shape[1] - 1,
    img_coords[:, -1] >= test.tth_arr.shape[0] - 1
], axis=0)

img_coords_catalog = []
base = 0
for i in range(len(orientations)):
    base_i = base + len(tth_list[i])
    i_img_coords = img_coords[base : base_i][~bound_mask[base : base_i]]
    img_coords_catalog.append(i_img_coords)
    base = base_i

Finding orientations with 5 deg resolution...


  0%|          | 0/23328 [00:00<?, ?it/s]

100%|██████████| 23328/23328 [00:39<00:00, 584.01it/s]


In [758]:
fit_list = []
for i in tqdm(range(len(orientations))):
    fit_list.append(np.sum(test.map.images[*pixel_indices, *img_coords_catalog[i][:, ::-1].T]))

  0%|          | 0/9916 [00:00<?, ?it/s]

100%|██████████| 9916/9916 [00:00<00:00, 137211.02it/s]


In [735]:
from scipy.ndimage import gaussian_filter
#blurred_image = gaussian_filter(test.map.images[*pixel_indices], sigma=3)
blurred_image = gaussian_filter(test.map.spot_masks[*pixel_indices], sigma=3)

fit_list = []
for i in tqdm(range(len(orientations))):
    fit_list.append(np.sum(blurred_image[*img_coords_catalog[i][:, ::-1].T]))

  0%|          | 0/23328 [00:00<?, ?it/s]

100%|██████████| 23328/23328 [00:00<00:00, 138066.94it/s]


In [618]:
fit_list = []
blank_image = np.zeros((test.map.image_shape), dtype=np.bool_)
for i in tqdm(range(len(orientations))):

    v_minus = 1
    v_plus = 1
    h_minus = 1
    h_plus = 1

    mask = blank_image.copy()
    coords = img_coords_catalog[i][:, ::-1]

    for coord in coords:

        coord_v = coord[0]
        coord_h = coord[1]

        if coord_v == 0:
            v_minus = 0
        if coord_h == 0:
            h_minus = 0
        if coord_v == test.map.image_shape[0] - 1:
            v_plus = 0
        if coord_h == test.map.image_shape[1] - 1:
            h_plus = 0
        

        mask[coord_v - v_minus : coord_v + v_plus, coord_h - h_minus : coord_h + h_plus] = True

    fit_list.append(np.sum(test.map.images[*pixel_indices][mask]))

100%|██████████| 186624/186624 [02:47<00:00, 1112.14it/s]


In [ ]:
# SLOW

fit_list = []
blank_image = np.zeros((test.map.image_shape), dtype=np.bool_)
for i in tqdm(range(len(orientations))):
    mask = blank_image.copy()
    mask[*img_coords_catalog[i][:, ::-1].T] = True

    mask = expand_labels(mask, 5)
    fit_list.append(np.sum(test.map.images[*pixel_indices][mask]))

In [ ]:
# SLOW

from xrdmaptools.utilities.math import circular_mask

fit_list = []
for i in tqdm(range(len(orientations))):
    mask_list = []
    for coord in img_coords_catalog[i][:, ::-1]:
        mask_list.append(circular_mask(test.map.image_shape, coord, 2))
    circ_mask = np.sum(np.asarray(mask_list), axis=0, dtype=np.bool_)
    fit_list.append(np.sum(test.map.images[*pixel_indices][circ_mask]))

In [759]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200, subplot_kw={'projection':'3d'})

plot_mask = np.array(fit_list) > 2.5

ax.scatter(*np.asarray(orientations)[plot_mask].T, c=np.array(fit_list)[plot_mask], s=1, alpha=0.5)

plt.show()

In [757]:
best_orientations = np.asarray(orientations)[plot_mask]

print(f'Finding new orientations...')
step /= 2
new_orientations = []
for orientation in best_orientations:
    phi1, PHI, phi2 = orientation
    new_phi1 = [phi1 - step, phi1, phi1 + step]
    new_PHI = [PHI - step, PHI, PHI + step]
    new_phi2 = [phi2 - step, phi2, phi2 + step]

    sub_orientations = product(new_phi1, new_PHI, new_phi2)

    for sub_orientation in sub_orientations:
        if sub_orientation not in new_orientations:
            new_orientations.append(sub_orientation)
    
    orientations = new_orientations

tth_list, chi_list = [], []
tth_all, chi_all = [], []
for orientation in tqdm(orientations):
    tth, chi = nearest_polar_on_ewald(euler_rotation(all_qs, *orientation),
                                            test.wavelength, near_thresh=0.05,
                                            degrees=True)
    
    nan_mask = np.any([np.isnan(tth), np.isnan(chi)], axis=0)
    tth = tth[~nan_mask]
    chi = chi[~nan_mask]
    
    tth_list.append(tth)
    tth_all.extend(tth)
    chi_list.append(chi)
    chi_all.extend(chi)
    #min_list.append(np.sum(test.map.images[*pixel_indices, *img_coords[:, ::-1].T]))

img_coords = estimate_image_coords(np.array([tth_all, chi_all]).T, test.tth_arr, test.chi_arr)

bound_mask = np.any([
    img_coords[:, 0] <= 0,
    img_coords[:, -1] <= 0,
    img_coords[:, 0] >= test.tth_arr.shape[1] - 1,
    img_coords[:, -1] >= test.tth_arr.shape[0] - 1
], axis=0)

img_coords_catalog = []
base = 0
for i in range(len(orientations)):
    base_i = base + len(tth_list[i])
    i_img_coords = img_coords[base : base_i][~bound_mask[base : base_i]]
    img_coords_catalog.append(i_img_coords)
    base = base_i

Finding new orientations...


100%|██████████| 9916/9916 [00:16<00:00, 594.22it/s]


In [76]:
from xrdmaptools.geometry.geometry import estimate_image_coords

pixel_indices = [4, 11]

pixel_df = test.pixel_spots(pixel_indices).dropna().sort_values('fit_integrated', ascending=False)

fig, ax = test.plot_image(pixel_indices, spots=True, contours=True, return_plot=True)

ind = np.argmax(pixel_df[['fit_integrated']])
ind = 7
plot_x, plot_y = estimate_image_coords([[pixel_df[['fit_tth0']].values[ind][0],
                                         pixel_df[['fit_chi0']].values[ind][0]]],
                                         test.tth_arr, test.chi_arr)[0]

ax.scatter(plot_x, plot_y, s=1, c='green')

plt.show()

In [20]:
np.linalg.norm(phase.Q([[1, 0, 0], [0, 1, 0], [0, 0, 1]]), axis=0)

array([0.55534606, 1.63752549, 0.55930081])

In [424]:
def _index_spots(spot_qs, rotation, ref_qs, ref_hkls, indexed_spots=None, indexed_hkls=None):

    if indexed_spots is None:
        indexed_spots = []
    if indexed_hkls is None:
        indexed_hkls = []
    
    rot_spot_qs = spot_qs @ rotation.T

    dist = euclidean_distances(rot_spot_qs, ref_qs)
    # higher threshold to account for chi value changes
    dist[dist > 10 * near_thresh] = np.inf
    matches = np.argmin(dist, axis=1)
    dist_mins = np.min(dist, axis=1)

    #print(f'{len(indexed_spots)=}')
    #print(f'{len(indexed_hkls)=}')
    # This is to add pair indices without know what the hkls necessarily are
    if len(indexed_spots) > 0 and indexed_hkls == []:
        for i in indexed_spots:
            indexed_hkls.append(ref_hkls[matches[i]])
        if indexed_hkls[0] == indexed_hkls[1]:
            raise RuntimeError

    #print(f'{len(indexed_spots)=}')
    #print(f'{len(indexed_hkls)=}')
    for i, val in enumerate(matches):
        if (ref_hkls[val] in indexed_hkls
            or i in indexed_spots
            or np.isinf(dist_mins[i])):
            continue
        
        if np.sum(matches == val) == 1:
            indexed_spots.append(i)
            indexed_hkls.append(ref_hkls[val])
        elif np.sum(matches == val) > 1:
            mask = ((matches == val)
                    & (dist_mins == np.min(dist_mins[matches == val])))
            ind = np.where(mask)[0][0]
            indexed_spots.append(ind)
            indexed_hkls.append(ref_hkls[val])

    return indexed_spots, indexed_hkls

In [440]:
# Pairwise indexing

from scipy.spatial.transform import Rotation
from itertools import product, combinations
from sklearn.metrics.pairwise import euclidean_distances
from xrdmaptools.crystal.Phase import generate_reciprocal_lattice
from xrdmaptools.utilities.image_corrections import rescale_array


pixel_indices = [7, 22]

pixel_df = test.pixel_spots(pixel_indices).dropna().sort_values('fit_integrated', ascending=False)

if len(pixel_df) < 2:
    raise ValueError('Not enough spots for indexing!')

spot_qs = pixel_df[['qx', 'qy', 'qz']].values
phase = test.phases['stibnite']
near_thresh = 0.05
min_rssd = 0.15
max_iterations = 50

if phase.reflections is None:
    phase.get_hkl_reflections(tth_range=(np.min(test.tth_arr), np.max(test.tth_arr)))

# Semi-useful...
all_hkls, all_qs, all_fs = generate_reciprocal_lattice(phase, tth_range=(np.min(test.tth_arr), np.max(test.tth_arr)))

# Minimum step size in q-space. Maybe...
min_q = np.min(np.linalg.norm(phase.Q([[1, 0, 0], [0, 1, 0], [0, 0, 1]]), axis=0))

# find potential matces within a threshold
phase_q_vals = phase.reflections['q']
spot_q_vals = np.linalg.norm(spot_qs, axis=1)
diff_arr = np.abs(spot_q_vals[:, np.newaxis] - phase_q_vals[np.newaxis, :])
pot_match = diff_arr < near_thresh

# Distinguish by phase kind of
phase_mask = np.any(pot_match, axis=1)
pot_match = pot_match[phase_mask]
spot_qs = np.array(spot_qs)[phase_mask]

# Find matching reflections and convert to q-space (with 2pi factor)
simple_q_calc = []
all_q_calc = []
for pot_match_i in pot_match:
    if not np.any(pot_match_i):
        continue
    match_ind = np.where(pot_match_i)[0]
    hkls = [phase.reflections['hkl'][ind] for ind in match_ind]
    simple_q_calc.append(phase.Q(hkls))

    # Add equivalent hkls
    ext_hkls = []
    [ext_hkls.extend(list(phase.lattice.equivalent_hkls(hkl))) for hkl in hkls];
    hkls = ext_hkls

    q_calc = phase.Q(hkls)
    all_q_calc.append(q_calc)

if len(all_q_calc) < 1:
    raise ValueError('No reflections close to found spots!')

grain_list = []
remaining_spots = list(range(len(spot_qs)))
while len(remaining_spots) > 0:
    print('Indexing new grain')
    rem_spot_qs = spot_qs[remaining_spots]

    # Indexing only possible on two spots
    # If only one remaining, mark as unindexed
    if len(remaining_spots) == 1:
        grain_list.append((remaining_spots, [], []))
        remaining_spots = []

    #print('Generating new pairs')
    pairs_indices = list(combinations(range(len(remaining_spots)), 2))

    for pair in pairs_indices:
        spot0, spot1 = rem_spot_qs[list(pair)]

        dist = np.sqrt((spot0[0] - spot1[0])**2
                    + (spot0[1] - spot1[1])**2
                    + (spot0[2] - spot1[2])**2)
        
        # Only consider crystallographically feasible distnaces
        if dist < (min_q * 0.85): # within 15 % error
            print('q-spacing too small')
            if pair == pairs_indices[-1]:
                print(f'Exhausted pairs')
                grain_list.append((remaining_spots, [], []))
                remaining_spots = []
            continue

        fit_q_calc = [simple_q_calc[remaining_spots[pair[0]]],
                      all_q_calc[remaining_spots[pair[1]]]]

        combos = list(product(*fit_q_calc))

        rot_list, rssd_list = [], []
        valid_combos = []
        for q_calc in combos:
            if np.sum(np.abs(np.cross(*q_calc))) < 1e-8:
                continue

            rot, rssd = Rotation.align_vectors(q_calc, rem_spot_qs[list(pair)])
            rot_list.append(rot.as_matrix())
            rssd_list.append(rssd)
            valid_combos.append(q_calc)

        # Collect best fit guess hkls
        rssd_list = np.asarray(rssd_list)
        if not np.any(rssd_list < min_rssd):
            print('All possible alignments are bad')
            if pair == pairs_indices[-1]:
                print(f'Exhausted pairs')
                grain_list.append((remaining_spots, [], []))
                remaining_spots = []    
            continue

        min_rssd_list = np.round(rssd_list[rssd_list < min_rssd], 10)
        min_q_calcs = np.round(np.array(valid_combos)[rssd_list < min_rssd], 10)
        min_rot_list = np.array(rot_list)[rssd_list < min_rssd]

        # Sort unique fits by minimum rssd
        # This biases towards equivalent positive values
        sorted_min_rssd_list = sorted(np.unique(min_rssd_list))
        sorted_min_q_calcs = [min_q_calcs[np.where(min_rssd_list == val)[0][0]]
                            for val in sorted_min_rssd_list]
        sorted_min_rot_list = [min_rot_list[np.where(min_rssd_list == val)[0][0]]
                            for val in sorted_min_rssd_list]

        # Setup features for refinement
        rotation_list = sorted_min_rot_list
        indexed_spots_catalog = []
        indexed_hkls_catalog = []
        rssd_list = []
        misorientation_list = [] # not currently used
        best_indexed = 0

        # Refine orientation!
        REFINE = True
        iteration = 0
        while REFINE:
            # Setup comparison features for refinement
            new_rotation_list = []
            new_indexed_spots_catalog = []
            new_indexed_hkls_catalog = []
            new_rssd_list = []
            new_misorientation_list = [] # not currently used
            print(f'{iteration=}')
            for rot in rotation_list:
                #print(rot)
                
                # Forces pair to be included
                indexed_spots = list(pair)
                #indexed_spots = []
                indexed_spots, indexed_hkls = _index_spots(
                                                rem_spot_qs,
                                                rot,
                                                all_qs,
                                                all_hkls,
                                                indexed_spots=indexed_spots)
                
                new_indexed_spots_catalog.append(indexed_spots)
                new_indexed_hkls_catalog.append(indexed_hkls)

                new_rot, rssd = Rotation.align_vectors(phase.Q(indexed_hkls), rem_spot_qs[indexed_spots])
                new_rotation_list.append(new_rot.as_matrix())
                new_rssd_list.append(rssd)
                misori = rot @ new_rot.as_matrix().T
                new_misorientation_list.append(np.degrees(np.arccos(0.5 * (np.trace(misori) - 1))))

                #if len(remaining_spots) == 4:
                #    raise
            
            # Best candidate of current refinment
            new_best_indexed = np.argmin(new_rssd_list)
            
            # Force at least two iterations
            if iteration == 0:
                pass
            elif iteration == max_iterations:
                print('WARNING: Refinement reached max number of iterations.')
                REFINE = False
            elif len(new_indexed_spots_catalog[new_best_indexed]) > len(indexed_spots_catalog[best_indexed]):
            #elif new_rssd_list[new_best_indexed] < rssd_list[best_indexed]:
                # Keep updating
                pass
            else:
                REFINE = False
                print(f'Refinement complete after {iteration + 1} iterations.')
                # Do not redefine values
                break
            #else:
            #    # Compare values and stop if no new spots
            #    if (best_indexed == new_best_indexed
            #        and len(indexed_spots_catalog[best_indexed])
            #        <= len(new_indexed_spots_catalog[new_best_indexed])):
            #        REFINE = False # No changes, stop refinement
            #        print(f'Refinement complete after {iteration + 1} iterations.')

            # Redefine values
            rotation_list = new_rotation_list.copy()
            indexed_spots_catalog = new_indexed_spots_catalog.copy()
            indexed_hkls_catalog = new_indexed_hkls_catalog.copy()
            rssd_list = new_rssd_list.copy()
            misorientation_list = new_misorientation_list.copy() # not currently used
            best_indexed = new_best_indexed
            iteration += 1

        grain_list.append((np.array(remaining_spots)[indexed_spots_catalog[best_indexed]],
                           indexed_hkls_catalog[best_indexed],
                           rotation_list[best_indexed]))
        
        for spot in np.array(remaining_spots)[indexed_spots_catalog[best_indexed]]:
            remaining_spots.remove(spot)

        print('testing pair == pairs_indices')
        if pair == pairs_indices[-1]:
            print(f'Exhausted pairs')
            grain_list.append((remaining_spots, [], []))
            remaining_spots = []
        else:
            break

Indexing new grain
q-spacing too small
iteration=0
iteration=1
iteration=2
Refinement complete after 3 iterations.
testing pair == pairs_indices
Indexing new grain
iteration=0
iteration=1
Refinement complete after 2 iterations.
testing pair == pairs_indices
Indexing new grain
iteration=0
iteration=1
Refinement complete after 2 iterations.
testing pair == pairs_indices
Indexing new grain
iteration=0
iteration=1
Refinement complete after 2 iterations.
testing pair == pairs_indices
Exhausted pairs


In [441]:
grain_list

[(array([ 0,  2,  4,  6, 11,  8, 16, 14, 15]),
  [(1, 1, 4),
   (3, 0, 8),
   (3, 0, 9),
   (3, 0, 7),
   (2, 1, 11),
   (2, 1, 7),
   (2, 1, 10),
   (3, 0, 11),
   (2, 1, 8)],
  array([[-0.52098044, -0.27260042,  0.80886859],
         [-0.15645596,  0.96207398,  0.22346185],
         [-0.83910721, -0.01013305, -0.54387169]])),
 (array([ 1,  3,  7, 10]),
  [(4, 1, 1), (9, 0, 4), (10, 1, 5), (9, 1, 4)],
  array([[-0.98534528, -0.08573322,  0.14746013],
         [-0.09866673,  0.99167455, -0.08274333],
         [-0.13913861, -0.09608016, -0.98560086]])),
 (array([5, 9]),
  [(4, 0, 9), (5, 1, 10)],
  array([[-0.65261187,  0.28578136,  0.70173126],
         [ 0.00267471,  0.92700584, -0.37503736],
         [-0.75768766, -0.24287691, -0.60573939]])),
 (array([12, 13]),
  [(3, 3, 3), (3, 3, 4)],
  array([[-0.54827813, -0.06186442,  0.83400473],
         [-0.82516935,  0.20215411, -0.52747442],
         [-0.13596558, -0.97739783, -0.1618853 ]])),
 ([], [], [])]

In [ ]:
spot_qs = rem_spot_qs
rotation = rot
ref_qs = all_qs
ref_hkls = all_hkls
indexed_spots=list(pair)
indexed_hkls=None

    if indexed_spots is None:
        indexed_spots = []
    if indexed_hkls is None:
        indexed_hkls = []
    
    rot_spot_qs = spot_qs @ rotation.T

    dist = euclidean_distances(rot_spot_qs, ref_qs)
    # higher threshold to account for chi value changes
    dist[dist > 10 * near_thresh] = np.inf
    matches = np.argmin(dist, axis=1)
    dist_mins = np.min(dist, axis=1)

    #print(f'{len(indexed_spots)=}')
    #print(f'{len(indexed_hkls)=}')
    # This is to add pair indices without know what the hkls necessarily are
    if len(indexed_spots) > 0 and indexed_hkls == []:
        for i in indexed_spots:
            indexed_hkls.append(ref_hkls[matches[i]])
        if indexed_hkls[0] == indexed_hkls[1]:
            raise RuntimeError

    #print(f'{len(indexed_spots)=}')
    #print(f'{len(indexed_hkls)=}')
    for i, val in enumerate(matches):
        if (ref_hkls[val] in indexed_hkls
            or i in indexed_spots
            or np.isinf(dist_mins[i])):
            continue
        
        if np.sum(matches == val) == 1:
            indexed_spots.append(i)
            indexed_hkls.append(ref_hkls[val])
        elif np.sum(matches == val) > 1:
            mask = ((matches == val)
                    & (dist_mins == np.min(dist_mins[matches == val])))
            ind = np.where(mask)[0][0]
            indexed_spots.append(ind)
            indexed_hkls.append(ref_hkls[val])

In [852]:
rotation_list

[array([[-0.75182462,  0.42109117, -0.50738739],
        [-0.56928022, -0.02628127,  0.82172339],
        [ 0.33268568,  0.90663748,  0.25947778]])]

In [855]:
from matplotlib import colormaps, color_sequences

from xrdmaptools.geometry.geometry import estimate_image_coords

pixel_indices = [12, 104]

pixel_df = test.pixel_spots(pixel_indices).dropna().sort_values('fit_integrated', ascending=False)

plot_x, plot_y = estimate_image_coords(pixel_df[['fit_tth0', 'fit_chi0']].values,
                                       test.tth_arr, test.chi_arr).T

fig, ax = test.plot_image(pixel_indices, spots=False, contours=True, return_plot=True)

for i in range(len(grain_list)):
    c = [color_sequences['tab20'][i],] * len(grain_list[i][0])
    ax.scatter(plot_x[grain_list[i][0]], plot_y[grain_list[i][0]], c=c, s=5, label=f'grain {i}')

ax.legend()
plt.show()

In [872]:
def pairwise_indexing(xrdmap, pixel_indices, phase, near_thresh=0.05, min_rssd=0.15, max_iterations=50):

    from scipy.spatial.transform import Rotation
    from itertools import product, combinations
    from sklearn.metrics.pairwise import euclidean_distances
    from xrdmaptools.crystal.Phase import generate_reciprocal_lattice
    from xrdmaptools.utilities.image_corrections import rescale_array

    pixel_df = xrdmap.pixel_spots(pixel_indices).dropna().sort_values('fit_integrated', ascending=False)

    if len(pixel_df) < 2:
        raise ValueError('Not enough spots for indexing!')

    spot_qs = pixel_df[['qx', 'qy', 'qz']].values
    #near_thresh = 0.05
    #min_rssd = 0.15
    #max_iterations = 50

    if phase.reflections is None:
        phase.get_hkl_reflections(tth_range=(np.min(test.tth_arr), np.max(test.tth_arr)))

    # Semi-useful...
    all_hkls, all_qs, all_fs = generate_reciprocal_lattice(phase, tth_range=(np.min(test.tth_arr), np.max(test.tth_arr)))

    # Minimum step size in q-space. Maybe...
    min_q = np.min(np.linalg.norm(phase.Q([[1, 0, 0], [0, 1, 0], [0, 0, 1]]), axis=0))

    # find potential matces within a threshold
    phase_q_vals = phase.reflections['q']
    spot_q_vals = np.linalg.norm(spot_qs, axis=1)
    diff_arr = np.abs(spot_q_vals[:, np.newaxis] - phase_q_vals[np.newaxis, :])
    pot_match = diff_arr < near_thresh

    # Distinguish by phase kind of
    phase_mask = np.any(pot_match, axis=1)
    pot_match = pot_match[phase_mask]
    spot_qs = np.array(spot_qs)[phase_mask]

    # Find matching reflections and convert to q-space (with 2pi factor)
    simple_q_calc = []
    all_q_calc = []
    for pot_match_i in pot_match:
        if not np.any(pot_match_i):
            continue
        match_ind = np.where(pot_match_i)[0]
        hkls = [phase.reflections['hkl'][ind] for ind in match_ind]
        simple_q_calc.append(phase.Q(hkls))

        # Add equivalent hkls
        ext_hkls = []
        [ext_hkls.extend(list(phase.lattice.equivalent_hkls(hkl))) for hkl in hkls];
        hkls = ext_hkls

        q_calc = phase.Q(hkls)
        all_q_calc.append(q_calc)

    if len(all_q_calc) < 1:
        raise ValueError('No reflections close to found spots!')
        grain_list = [[[], [], []]]
        return grain_list

    grain_list = []
    remaining_spots = list(range(len(spot_qs)))
    while len(remaining_spots) > 0:
        #print('Indexing new grain')
        rem_spot_qs = spot_qs[remaining_spots]

        # Indexing only possible on two spots
        # If only one remaining, mark as unindexed
        if len(remaining_spots) == 1:
            grain_list.append((remaining_spots, [], []))
            remaining_spots = []

        #print('Generating new pairs')
        pairs_indices = list(combinations(range(len(remaining_spots)), 2))

        for pair in pairs_indices:
            spot0, spot1 = rem_spot_qs[list(pair)]

            dist = np.sqrt((spot0[0] - spot1[0])**2
                        + (spot0[1] - spot1[1])**2
                        + (spot0[2] - spot1[2])**2)
            
            # Only consider crystallographically feasible distnaces
            if dist < (min_q * 0.85): # within 15 % error
                if pair == pairs_indices[-1]:
                    grain_list.append((remaining_spots, [], []))
                    remaining_spots = []
                continue

            fit_q_calc = [simple_q_calc[remaining_spots[pair[0]]],
                        all_q_calc[remaining_spots[pair[1]]]]

            combos = list(product(*fit_q_calc))

            rot_list, rssd_list = [], []
            valid_combos = []
            for q_calc in combos:
                if np.sum(np.abs(np.cross(*q_calc))) < 1e-8:
                    continue
                rot, rssd = Rotation.align_vectors(q_calc, rem_spot_qs[list(pair)])
                rot_list.append(rot.as_matrix())
                rssd_list.append(rssd)
                valid_combos.append(q_calc)

            # Collect best fit guess hkls
            rssd_list = np.asarray(rssd_list)
            if not np.any(rssd_list < min_rssd):
                if pair == pairs_indices[-1]:
                    grain_list.append((remaining_spots, [], []))
                    remaining_spots = []
                continue
            min_rssd_list = np.round(rssd_list[rssd_list < min_rssd], 10)
            min_q_calcs = np.round(np.array(valid_combos)[rssd_list < min_rssd], 10)
            min_rot_list = np.array(rot_list)[rssd_list < min_rssd]

            # Sort unique fits by minimum rssd
            # This biases towards equivalent positive values
            sorted_min_rssd_list = sorted(np.unique(min_rssd_list))
            sorted_min_q_calcs = [min_q_calcs[np.where(min_rssd_list == val)[0][0]]
                                for val in sorted_min_rssd_list]
            sorted_min_rot_list = [min_rot_list[np.where(min_rssd_list == val)[0][0]]
                                for val in sorted_min_rssd_list]

            # Setup features for refinement
            rotation_list = sorted_min_rot_list
            indexed_spots_catalog = []
            indexed_hkls_catalog = []
            rssd_list = []
            misorientation_list = [] # not currently used
            best_indexed = 0

            # Refine orientation!
            REFINE = True
            iteration = 0
            while REFINE:
                # Setup comparison features for refinement
                new_rotation_list = []
                new_indexed_spots_catalog = []
                new_indexed_hkls_catalog = []
                new_rssd_list = []
                new_misorientation_list = [] # not currently used
                #print(f'{iteration=}')
                for rot in rotation_list:
                    #print(rot)
                    
                    # Forces pair to be included
                    indexed_spots = list(pair)
                    indexed_spots = []
                    indexed_spots, indexed_hkls = _index_spots(
                                                    rem_spot_qs,
                                                    rot,
                                                    all_qs,
                                                    all_hkls,
                                                    indexed_spots=indexed_spots)
                    
                    new_indexed_spots_catalog.append(indexed_spots)
                    new_indexed_hkls_catalog.append(indexed_hkls)

                    new_rot, rssd = Rotation.align_vectors(phase.Q(indexed_hkls), rem_spot_qs[indexed_spots])
                    new_rotation_list.append(new_rot.as_matrix())
                    new_rssd_list.append(rssd)
                    misori = rot @ new_rot.as_matrix().T
                    new_misorientation_list.append(np.degrees(np.arccos(0.5 * (np.trace(misori) - 1))))

                    #if len(remaining_spots) == 4:
                    #    raise
                
                # Best candidate of current refinment
                new_best_indexed = np.argmin(new_rssd_list)
                
                # Force at least two iterations
                if iteration == 0:
                    pass
                elif iteration == max_iterations:
                    #print('WARNING: Refinement reached max number of iterations.')
                    REFINE = False
                elif len(new_indexed_spots_catalog[new_best_indexed]) > len(indexed_spots_catalog[best_indexed]):
                #elif new_rssd_list[new_best_indexed] < rssd_list[best_indexed]:
                    # Keep updating
                    pass
                else:
                    REFINE = False
                    #print(f'Refinement complete after {iteration + 1} iterations.')
                    # Do not redefine values
                    break
                #else:
                #    # Compare values and stop if no new spots
                #    if (best_indexed == new_best_indexed
                #        and len(indexed_spots_catalog[best_indexed])
                #        <= len(new_indexed_spots_catalog[new_best_indexed])):
                #        REFINE = False # No changes, stop refinement
                #        print(f'Refinement complete after {iteration + 1} iterations.')

                # Redefine values
                rotation_list = new_rotation_list.copy()
                indexed_spots_catalog = new_indexed_spots_catalog.copy()
                indexed_hkls_catalog = new_indexed_hkls_catalog.copy()
                rssd_list = new_rssd_list.copy()
                misorientation_list = new_misorientation_list.copy() # not currently used
                best_indexed = new_best_indexed
                iteration += 1

            grain_list.append((np.array(remaining_spots)[indexed_spots_catalog[best_indexed]],
                            indexed_hkls_catalog[best_indexed],
                            rotation_list[best_indexed]))
            
            for spot in np.array(remaining_spots)[indexed_spots_catalog[best_indexed]]:
                remaining_spots.remove(spot)

            if pair == pairs_indices[-1]:
                grain_list.append((remaining_spots, [], []))
                remaining_spots = []
            else:
                break

    return grain_list

In [880]:
# pairwise indexing across full map

from sklearn.metrics.pairwise import euclidean_distances
from tqdm import tqdm
from xrdmaptools.utilities.utilities import combine_nearby_spots
from xrdmaptools.crystal.Phase import generate_reciprocal_lattice
from itertools import product
from scipy.spatial.transform import Rotation

phase = test.phases['stibnite']

if phase.reflections is None:
    phase.get_hkl_reflections(tth_range=(np.min(test.tth_arr), np.max(test.tth_arr)))

euler_map = np.empty((*test.map.map_shape, 3))
fit_map = np.empty(test.map.map_shape)

orientation_map = np.empty((*test.map.map_shape, 3, 3))
nan_orientation = np.empty((3, 3))
nan_orientation[:] = np.nan

for index in tqdm(range(test.map.num_images)):
    indices = np.unravel_index(index, test.map.map_shape)
    pixel_df = test.pixel_spots(indices).dropna()
    
    # Conditional to avoid too few spots for theoretical indexing
    if len(pixel_df) < 2:
        orientation_map[indices] = nan_orientation
        continue

    # Combine nearby spots for better indexing speed
    # Will not work with current definition of pairwise indexing
    #spot_qs = pixel_df[['qx', 'qy', 'qz']].values
    #spot_ints = pixel_df[['guess_int']].values

    #spot_qs, spot_ints = combine_nearby_spots(spot_qs, spot_ints, max_dist=0.1, max_neighbors=np.inf)

    # Sort spots from largest to smallest intensity
    #zipped = list(zip(spot_ints, spot_qs))
    #zipped.sort(reverse=True)
    #spot_ints, spot_qs = zip(*zipped)
    #spot_ints = list(spot_ints)
    #spot_qs = list(spot_qs)
    
    
    grain_list = pairwise_indexing(test,
                                   indices,
                                   phase,
                                   near_thresh=0.05,
                                   min_rssd=0.15,
                                   max_iterations=10)
    
    if isinstance(grain_list[0][-1], list):
        orientation_map[indices] = nan_orientation
    else:
        orientation_map[indices] = grain_list[0][-1]

100%|██████████| 3381/3381 [21:44<00:00,  2.59it/s]  


In [891]:
vecs = np.asarray(spot_qs)

In [948]:
are_collinear(spot_qs)

False

In [947]:
def are_collinear(vectors):
    vecs = np.asarray(vectors)
    collinear_flag = True

    # Probably faster. Not easy to perform pairwise
    if len(vecs) == 2:
        if np.sum(np.abs(np.cross(*vecs))) > 1e-8:
            collinear_flag = False
        return collinear_flag

    # Pairwise analysis fo list of vectors
    const_list = []
    for ind in range(vecs.shape[1]):
        vecs_axis = vecs[:, ind]
        if not np.any(vecs_axis == 0):
            const = np.abs(vecs_axis[:, np.newaxis] / vecs_axis[np.newaxis, :])
            const_list.append(np.round(const, 3))

    combos = list(combinations(range(vecs.shape[1]), 2))
    if len(combos) > 1:
        combos.pop(-1) # last index is redundant

    for combo in combos:
        if np.any(const_list[combo[0]] != const_list[combo[1]]):
            collinear_flag = False
            break
        
    return collinear_flag

In [914]:
from itertools import permutations

In [919]:
list(combinations(range(vecs.shape[1]), 2))

[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]

In [912]:
const_list

[array([[1.        , 0.98320686, 1.0606034 , ..., 0.59548845, 0.57227492,
         0.56457005],
        [1.01707997, 1.        , 1.07871848, ..., 0.60565937, 0.58204936,
         0.57421289],
        [0.94285951, 0.92702593, 1.        , ..., 0.56146194, 0.53957485,
         0.53231024],
        ...,
        [1.6792937 , 1.65109308, 1.78106462, ..., 1.        , 0.96101767,
         0.94807893],
        [1.7474119 , 1.71806736, 1.85331101, ..., 1.0405636 , 1.        ,
         0.98653643],
        [1.77125938, 1.74151437, 1.87860372, ..., 1.0547645 , 1.01364731,
         1.        ]]),
 array([[1.        , 1.13504174, 0.7623954 , ..., 0.92240448, 0.96889377,
         1.18833152],
        [0.88102487, 1.        , 0.67168931, ..., 0.81266129, 0.85361951,
         1.04694963],
        [1.31165534, 1.48878355, 1.        , ..., 1.20987675, 1.27085469,
         1.55868138],
        ...,
        [1.0841231 , 1.23052496, 0.82653047, ..., 1.        , 1.05040012,
         1.28829765],
        [1.0

In [901]:
np.mean(first_const).

0.5071963191171929

In [909]:
np.unique(np.round(first_const, 3))

array([0.309, 0.31 , 0.312, 0.313, 0.314, 0.315, 0.316, 0.325, 0.326,
       0.327, 0.328, 0.329, 0.33 , 0.331, 0.332, 0.333, 0.334, 0.335,
       0.336, 0.337, 0.338, 0.355, 0.356, 0.357, 0.358, 0.359, 0.36 ,
       0.361, 0.362, 0.363, 0.364, 0.365, 0.366, 0.367, 0.368, 0.369,
       0.37 , 0.371, 0.488, 0.489, 0.49 , 0.491, 0.492, 0.493, 0.494,
       0.495, 0.496, 0.497, 0.498, 0.499, 0.5  , 0.501, 0.502, 0.503,
       0.504, 0.505, 0.506, 0.507, 0.508, 0.509, 0.62 , 0.621, 0.623,
       0.624, 0.625, 0.626, 0.627, 0.628, 0.629, 0.63 , 0.631, 0.632,
       0.654, 0.655, 0.656, 0.657, 0.658, 0.659, 0.66 , 0.661, 0.662,
       0.663, 0.664, 0.665, 0.666, 0.667, 0.668, 0.669, 0.67 , 0.671,
       0.672, 0.673, 0.674, 0.675, 0.676, 0.713, 0.714, 0.715, 0.716,
       0.717, 0.718, 0.719, 0.72 , 0.721, 0.722, 0.723, 0.724, 0.725,
       0.726, 0.727, 0.728, 0.729, 0.73 , 0.731, 0.732, 0.733, 0.734,
       0.735, 0.736, 0.737, 0.738, 0.739, 0.74 , 0.741, 0.742, 0.852,
       0.854, 0.856,

In [897]:
first_const.shape

(488, 488)

In [866]:
indices

(0, 69)

In [842]:
indices

(12, 104)

In [400]:
euler_map = np.empty((*test.map.map_shape, 3))

for index in range(test.map.num_images):
    indices = np.unravel_index(index, test.map.map_shape)
    
    euler = Rotation.from_matrix(orientation_map[indices]).as_euler('zxz', degrees=True)
    euler_map[indices] = euler

NameError: name 'orientation_map' is not defined

In [804]:
orientation_map

array([[[[        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan]],

        [[        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan]],

        [[        nan,         nan,         nan],
         [        nan,         nan,         nan],
         [        nan,         nan,         nan]],

        ...,

        [[-0.04724966, -0.01005939, -0.99883246],
         [-0.04157443, -0.999063  ,  0.01202838],
         [-0.99801755,  0.04209423,  0.04678718]],

        [[-0.04724966, -0.01005939, -0.99883246],
         [-0.04157443, -0.999063  ,  0.01202838],
         [-0.99801755,  0.04209423,  0.04678718]],

        [[-0.04724966, -0.01005939, -0.99883246],
         [-0.04157443, -0.999063  ,  0.01202838],
         [-0.99801755,  0.04209423,  0.04678718]]],


       [[[        nan,         nan,         nan],
         [        nan,

In [431]:
# Pairwise indexing

from scipy.spatial.transform import Rotation
from itertools import product, combinations
from sklearn.metrics.pairwise import euclidean_distances
from xrdmaptools.crystal.Phase import generate_reciprocal_lattice
from xrdmaptools.utilities.image_corrections import rescale_array


pixel_indices = [4, 11]

pixel_df = test.pixel_spots(pixel_indices).dropna().sort_values('fit_integrated', ascending=False)

if len(pixel_df) < 2:
    raise ValueError('Not enough spots for indexing!')

spot_qs = pixel_df[['qx', 'qy', 'qz']].values
phase = test.phases['stibnite']
near_thresh = 0.05
min_rssd = 0.2

if phase.reflections is None:
    phase.get_hkl_reflections(tth_range=(np.min(test.tth_arr), np.max(test.tth_arr)))

# Semi-useful...
all_hkls, all_qs, all_fs = generate_reciprocal_lattice(phase, tth_range=(np.min(test.tth_arr), np.max(test.tth_arr)))

# Minimum step size in q-space. Maybe...
min_q = np.min(np.linalg.norm(phase.Q([[1, 0, 0], [0, 1, 0], [0, 0, 1]]), axis=0))

# find potential matces within a threshold
phase_q_vals = phase.reflections['q']
spot_q_vals = np.linalg.norm(spot_qs, axis=1)
diff_arr = np.abs(spot_q_vals[:, np.newaxis] - phase_q_vals[np.newaxis, :])
pot_match = diff_arr < near_thresh

# Distinguish by phase kind of
phase_mask = np.any(pot_match, axis=1)
pot_match = pot_match[phase_mask]
spot_qs = np.array(spot_qs)[phase_mask]

# Find matching reflections and convert to q-space (with 2pi factor)
simple_q_calc = []
all_q_calc = []
for pot_match_i in pot_match:
    if not np.any(pot_match_i):
        continue
    match_ind = np.where(pot_match_i)[0]
    hkls = [phase.reflections['hkl'][ind] for ind in match_ind]
    simple_q_calc.append(phase.Q(hkls))

    # Add equivalent hkls
    ext_hkls = []
    [ext_hkls.extend(list(phase.lattice.equivalent_hkls(hkl))) for hkl in hkls];
    hkls = ext_hkls

    q_calc = phase.Q(hkls)
    all_q_calc.append(q_calc)

if len(all_q_calc) < 1:
    raise ValueError('No reflections close to found spots!')

grain_list = []
remaining_spots = list(range(len(spot_qs)))
while len(remaining_spots) > 0:
    grain_spots = []
    grain_hkl = []
    rem_spot_qs = spot_qs[remaining_spots]

    if len(remaining_spots) == 1:
        grain_list.append((remaining_spots, [], []))
        remaining_spots = []

    #print('Generating new pairs')
    pairs_indices = list(combinations(range(len(remaining_spots)), 2))

    for pair in pairs_indices:
        spot0, spot1 = rem_spot_qs[list(pair)]

        dist = np.sqrt((spot0[0] - spot1[0])**2
                    + (spot0[1] - spot1[1])**2
                    + (spot0[2] - spot1[2])**2)
        
        # Only consider crystallographically feasible distnaces
        if dist < (min_q * 0.85): # within 15 % error
            continue

        fit_q_calc = [simple_q_calc[remaining_spots[pair[0]]],
                      all_q_calc[remaining_spots[pair[1]]]]

        combos = list(product(*fit_q_calc))

        rot_list, rssd_list = [], []
        for q_calc in combos:
            rot, rssd = Rotation.align_vectors(q_calc, rem_spot_qs[list(pair)])
            rot_list.append(rot.as_matrix())
            rssd_list.append(rssd)

        # Collect best fit guess hkls
        rssd_list = np.asarray(rssd_list)
        if not np.any(rssd_list < min_rssd):
            continue
        min_rssd_list = np.round(rssd_list[rssd_list < min_rssd], 10)
        min_q_calcs = np.round(np.array(combos)[rssd_list < min_rssd], 10)
        min_rot_list = np.array(rot_list)[rssd_list < min_rssd]

        # Sort unique fits by minimum rssd
        # This biases towards equivalent positive values
        sorted_min_rssd_list = sorted(np.unique(min_rssd_list))
        sorted_min_q_calcs = [min_q_calcs[np.where(min_rssd_list == val)[0][0]]
                            for val in sorted_min_rssd_list]
        sorted_min_rot_list = [min_rot_list[np.where(min_rssd_list == val)[0][0]]
                            for val in sorted_min_rssd_list]
        
        # Attempt to index all spots with best found rotations
        indexed_spots_catalog = []
        indexed_hkls_catalog = []
        updated_rotations = []
        updated_rssd = []
        mis_mag_list = []
        for min_rot in sorted_min_rot_list:
            
            # Forces pair to be included
            indexed_spots = list(pair)
            indexed_spots = []
            indexed_spots, indexed_hkls = _index_spots(
                                            rem_spot_qs,
                                            min_rot,
                                            all_qs,
                                            all_hkls,
                                            indexed_spots=indexed_spots)

                
            indexed_spots_catalog.append(indexed_spots)
            indexed_hkls_catalog.append(indexed_hkls)

            rot, rssd = Rotation.align_vectors(phase.Q(indexed_hkls), rem_spot_qs[indexed_spots])
            updated_rotations.append(rot.as_matrix())
            updated_rssd.append(rssd)
            misori = min_rot @ rot.as_matrix().T
            mis_mag_list.append(np.degrees(np.arccos(0.5 * (np.trace(misori) - 1))))

        # Find indexing of most spots and recalculate rotation
        #best_indexed = np.argmax([len(l) for l in indexed_spots_catalog])
        best_indexed = np.argmin(updated_rssd)

        # Only one iteration of updates for now...
        # Check the updated rotations
        new_indexed_spots_catalog = []
        new_indexed_hkls_catalog = []
        new_updated_rotations = []
        new_updated_rssd = []
        new_mis_mag_list = []
        for ind in range(len(indexed_spots_catalog)):

            # Forces pair to be included
            indexed_spots = list(pair)
            indexed_spots = []
            indexed_spots, indexed_hkls = _index_spots(
                                            rem_spot_qs,
                                            updated_rotations[ind],
                                            all_qs,
                                            all_hkls,
                                            indexed_spots=indexed_spots)
            
            new_indexed_spots_catalog.append(indexed_spots)
            new_indexed_hkls_catalog.append(indexed_hkls)

            rot, rssd = Rotation.align_vectors(phase.Q(indexed_hkls), spot_qs[indexed_spots])
            new_updated_rotations.append(rot.as_matrix())
            new_updated_rssd.append(rssd)
            new_misori = updated_rotations[ind] @ rot.as_matrix().T
            new_mis_mag_list.append(np.degrees(np.arccos(0.5 * (np.trace(new_misori) - 1))))
        
        new_best_indexed = np.argmin(new_updated_rssd)
        grain_list.append((np.array(remaining_spots)[new_indexed_spots_catalog[new_best_indexed]],
                           new_indexed_hkls_catalog[new_best_indexed],
                           new_updated_rotations[new_best_indexed]))
        
        for spot in np.array(remaining_spots)[new_indexed_spots_catalog[new_best_indexed]]:
            remaining_spots.remove(spot)

        if pair == pairs_indices[-1]:
            grain_list.append((remaining_spots, [], []))
            remaining_spots = []
        else:
            break

In [432]:
grain_list

[(array([ 1,  2,  3, 31, 32,  9, 27, 11, 14, 13, 28, 18, 22, 33]),
  [(1, 1, 4),
   (2, 0, 7),
   (1, 0, 6),
   (2, 1, 7),
   (3, 0, 9),
   (1, -1, 4),
   (1, 1, 5),
   (2, -1, 7),
   (2, 0, 8),
   (3, 1, 9),
   (3, 1, 8),
   (4, 1, 10),
   (4, 0, 10),
   (4, 0, 11)],
  array([[-0.04727782, -0.00920148, -0.9988394 ],
         [-0.04084685, -0.99910335,  0.01113731],
         [-0.99804626,  0.04132599,  0.04685957]])),
 (array([ 0,  5,  6,  7, 19, 21, 35, 26, 29]),
  [(0, -1, -1),
   (-2, -1, 5),
   (-2, -1, 6),
   (0, -1, 7),
   (-2, -2, 8),
   (-3, -1, 2),
   (0, -2, 10),
   (-3, -2, 7),
   (-2, -2, 7)],
  array([[ 0.09399936,  0.42351898,  0.90099711],
         [ 0.76170021,  0.55216171, -0.33901362],
         [-0.6410748 ,  0.71815676, -0.27069165]])),
 (array([ 4, 23, 10, 12, 30, 17]),
  [(6, 0, 1), (9, 0, 2), (0, -1, -1), (8, 0, 2), (5, 0, -1), (8, 0, -1)],
  array([[-0.95322403,  0.0675869 , -0.29461154],
         [ 0.2960609 ,  0.01230855, -0.95508976],
         [-0.06092531, -0

In [238]:
from scipy.spatial.transform import Rotation
from itertools import product

def explicit_indexing(spot_qs, # Must already be sorted...
                      phase,
                      near_thresh=0.05,
                      required_spots=2,
                      check_equivalent=True):

    # Sort spots from largest to smallest intensity
    #zipped = list(zip(spot_ints, spot_qs))
    #zipped.sort(reverse=True)
    #spot_ints, spot_qs = zip(*zipped)

    # find potential matces within a threshold
    phase_q_vals = phase.reflections['q']
    spot_q_vals = np.linalg.norm(spot_qs, axis=1)
    diff_arr = np.abs(spot_q_vals[:, np.newaxis] - phase_q_vals[np.newaxis, :])
    pot_match = diff_arr < near_thresh

    # Distinguish by phase kind of
    phase_mask = np.any(pot_match, axis=1)
    pot_match = pot_match[phase_mask]
    spot_qs = np.array(spot_qs)[phase_mask]
    #spot_int = spot_ints[phase_mask]

    fit_q_meas = spot_qs[:required_spots]
    fit_q_calc = []
    for i, pot_match_i in enumerate(pot_match[:required_spots]):
        match_ind = np.where(pot_match_i)[0]
        hkls = [phase.reflections['hkl'][ind] for ind in match_ind]

        # Add equivalent potential indices. Only first index restricted
        # Not sure how much this actually helps...
        if check_equivalent and i > 0:
            ext_hkls = []
            [ext_hkls.extend(list(phase.lattice.equivalent_hkls(hkl))) for hkl in hkls];
            hkls = ext_hkls

        q_calc = phase.Q(hkls)
        fit_q_calc.append(q_calc)

    if len(fit_q_calc) > 0:
        combos = list(product(*fit_q_calc))

        rot_list, rssd_list = [], []
        for q_calc in combos:
            rot, rssd = Rotation.align_vectors(q_calc, fit_q_meas)
            rot_list.append(rot.as_matrix())
            rssd_list.append(rssd)

        min_ind = np.argmin(rssd_list)
        min_rssd = rssd_list[min_ind]
        best_orientation = rot_list[min_ind]

    else:
        min_rssd = np.nan
        best_orientation = np.nan
    #print(f'Best orientation found at {min_ind} with rssd of {rssd_list[min_ind]:.3f}')

    # This was worth it!
    #for combo in combos[min_ind][1:]:
    #    if phase.HKL(combo) not in phase.reflections['hkl']:
    #        print('Equivalent hkl used successfully. The extra computation was worth it!')
    #        break

    return best_orientation, min_rssd

In [244]:
# Explicit indexing across full map

from sklearn.metrics.pairwise import euclidean_distances
from tqdm import tqdm
from xrdmaptools.utilities.utilities import combine_nearby_spots
from xrdmaptools.crystal.Phase import generate_reciprocal_lattice
from itertools import product
from scipy.spatial.transform import Rotation

required_spots = 3
phase = test.phases['stibnite']

if phase.reflections is None:
    phase.get_hkl_reflections(tth_range=(np.min(test.tth_arr), np.max(test.tth_arr)))

all_hkls, all_qs, all_fs = generate_reciprocal_lattice(phase, tth_range=(np.min(test.tth_arr), np.max(test.tth_arr)))

dist = euclidean_distances(all_qs)
min_q = np.min(dist[dist > 0])

euler_map = np.empty((*test.map.map_shape, 3))
fit_map = np.empty(test.map.map_shape)

for index in tqdm(range(test.map.num_images)):
    indices = np.unravel_index(index, test.map.map_shape)
    phi1, PHI, phi2 = np.nan, np.nan, np.nan

    pixel_df = test.spots[(test.spots['map_x'] == indices[0])
                        & (test.spots['map_y'] == indices[1])].copy()
    pixel_df.dropna(inplace=True)
    
    # Conditional to avoid too few spots for theoretical indexing
    if len(pixel_df) < required_spots:
        euler_map[indices] = phi1, PHI, phi2
        continue
    
    spot_qs = pixel_df[['qx', 'qy', 'qz']].values
    spot_ints = pixel_df[['fit_integrated']].values
    #spot_chis = pixel_df[['fit_chi0']].values

    spot_qs, spot_ints = combine_nearby_spots(spot_qs, spot_ints, max_dist=0.1, max_neighbors=np.inf)

    # Sort spots from largest to smallest intensity
    zipped = list(zip(spot_ints, spot_qs))
    zipped.sort(reverse=True)
    spot_ints, spot_qs = zip(*zipped)
    spot_ints = list(spot_ints)
    spot_qs = list(spot_qs)

    dist_too_small = True
    while dist_too_small:
        if len(spot_qs) < required_spots:
            euler_map[indices] = phi1, PHI, phi2
            dist_too_small = False
            break
        # Conditional to avoid single spot from one blob
        dist = euclidean_distances(spot_qs)
        
        if dist[0, 1] < min_q:
            del spot_qs[1], spot_ints[1]
        else:
            dist_too_small = False

    if len(spot_qs) < required_spots:
        euler_map[indices] = phi1, PHI, phi2
        continue
    
    best_orientation, min_rssd = explicit_indexing(spot_qs,
                                                   phase,
                                                   near_thresh=0.05,
                                                   required_spots=required_spots,
                                                   check_equivalent=False)
    
    if not np.any(np.isnan(best_orientation)):
        best_euler = Rotation.from_matrix(best_orientation).as_euler('zxz', degrees=True)
        
        euler_map[indices] = best_euler
        fit_map[indices] = min_rssd
    else:
        euler_map[indices] = np.nan, np.nan, np.nan

 15%|█▌        | 524/3381 [00:02<00:21, 135.33it/s]C:\Users\emusterma\AppData\Local\Temp\ipykernel_2480\2468468959.py:48: UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors.
  rot, rssd = Rotation.align_vectors(q_calc, fit_q_meas)
 28%|██▊       | 960/3381 [00:05<00:16, 147.95it/s]C:\Users\emusterma\AppData\Local\Temp\ipykernel_2480\2468468959.py:48: UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors.
  rot, rssd = Rotation.align_vectors(q_calc, fit_q_meas)
 33%|███▎      | 1121/3381 [00:07<00:16, 137.04it/s]C:\Users\emusterma\AppData\Local\Temp\ipykernel_2480\2468468959.py:48: UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors.
  rot, rssd = Rotation.align_vectors(q_calc, fit_q_meas)
C:\Users\emusterma\AppData\Local\Temp\ipykernel_2480\2468468959.py:48: UserWarning: Optimal rotation is not uniquely or poorly defined for the given sets of vectors.
  rot, rssd

In [245]:
from xrdmaptools.crystal.orientation import g_func
g = g_func(*euler_map.reshape(test.map.num_images, 3).T)

In [881]:
g = orientation_map.reshape(-1, 3, 3)

In [246]:
ipole = [0, 0, 1]

colors, r, theta = [], [], []
for i in range(len(g)):
    
    # Take only part of the orientation matrix
    V = np.dot(g[i], ipole) # order is g, then ipole

    # Determine pixel color according to unit triangle
    R, G, B = 0, 0, 0
    base = 30 / 255 #all pixels are a bit brighter
    R=np.abs(V[2]) + base # referenced to crystallographic axes, but should be able to reference any axis
    G=np.abs(V[0]) + base
    B=np.abs(V[1]) + base

    # Normalize and brighten colors
    max_c = np.max([R,G,B])
    R = R / max_c
    G = G / max_c
    B = B / max_c
    
    # Setting pixel transparency if called
    A=1
    colors.append([R, G, B, A])

colors = np.asarray(colors)
colors = colors.reshape((*test.map.map_shape, 4))

In [247]:
fig, ax = plt.subplots(1, 1, figsize=(3, 3), dpi=200)

ax.imshow(colors)
ax.set_title(str(ipole))

plt.show()

In [387]:
test.plot_interactive_map(display_map=colors, img_vmin=0, img_vmax=0.1)

In [47]:
# Phase matching/mapping

#from sklearn.metrics.pairwise import euclidean_distances
from tqdm import tqdm

near_thresh = 0.1
sum_key = 'guess_int'
method = 'minimize_q_error'
#method = 'maximize_spots'

phase_keys = list(test.phases.keys())
phase_list = list(test.phases.values())

[phase.get_hkl_reflections(tth_range=(np.min(test.tth_arr), np.max(test.tth_arr)),
                               ignore_less=1)
        for phase in phase_list];

plot_map = np.zeros(test.map.map_shape)
plot_map[:] = 0

plot_dict = {}
for phase in phase_list:
    plot_dict[phase.name] = plot_map.copy()
plot_dict['unmatched'] = plot_map.copy()

for index in tqdm(range(test.map.num_images)):
    indices = np.unravel_index(index, test.map.map_shape)

    image = test.map.images[indices]
    pixel_df = test.pixel_spots(indices)
    #pixel_df = pixel_df.copy().dropna()
    num_spots = len(pixel_df)
    
    if num_spots > 1:
        spot_q_vals = np.linalg.norm(pixel_df[['qx', 'qy', 'qz']].values, axis=1)

        phase_diffs = []
        pot_matches = []
        phase_matches = []
        spot_matches = []
        for phase in phase_list:
            phase_q_vals = phase.reflections['q']
            #dist_arr = euclidean_distances(phase_q_vals.reshape(-1, 1), spot_q_vals.reshape(-1, 1))
            diff_arr = np.abs(phase_q_vals[:, np.newaxis] - spot_q_vals[np.newaxis, :])
            phase_diffs.append(diff_arr)
            pot_match = diff_arr < near_thresh
            pot_matches.append(pot_match)

            # Fraction of phase reflections explained by found spots
            #phase_matches.append(np.sum(pot_match / len(test.phases)))
            phase_matches.append(np.sum(np.any(pot_matches[-1], axis=1)) / len(phase_q_vals))

            # Number of spots explained by a given phase
            spot_matches.append(np.sum(np.any(pot_matches[-1], axis=0)))
            #raise

        # Track which spots have been matched
        rem_spot_mask = [True,] * num_spots

        if method in ['maximize_phase']:
            # Maximize phase matches
            # Should work better for polycrystalline patterns
            while (np.any(rem_spot_mask)) and (np.sum(phase_matches) > 0):
                # Check for more than 1 fully represented array
                if np.sum(np.array(phase_matches) == 1) > 1:
                    stacked_diffs = np.stack([np.min(diffs, axis=0) for diffs in phase_diffs])
                    spot_mask = np.min(stacked_diffs, axis=0) < near_thresh
                    phase_ind = np.argmin(stacked_diffs, axis=0)
                    phase_ind[~spot_mask] = -1
                    phase_mask = (np.array(phase_matches) == 1)
                    phase_count = [0,] * len(phase_list)
                    for ind in phase_ind:
                        if phase_mask[ind]:
                            phase_count[ind] += 1
                    max_ind = np.argmax(phase_count)
                else:
                    max_ind = np.argmax(phase_matches)

                # Index matching spots
                spot_mask = np.any(pot_matches[max_ind], axis=0)
                # Remove indexed spots from future use
                spot_mask *= rem_spot_mask
                rem_spot_mask *= ~spot_mask

                # Finally, find the value and remove reflections
                val = np.nansum(pixel_df[sum_key].values[spot_mask])
                phase_matches[max_ind] = 0

                # Fill value
                plot_dict[phase_list[max_ind].name][indices] = val

        elif method in ['maximize_spots']:
            # Maxmize spot_matches
            # Not sure when this one should work better
            while (np.any(rem_spot_mask)) and (np.sum(spot_matches) > 0):
                max_ind = np.argmax(spot_matches)
                # Index matching spots
                spot_mask = np.any(pot_matches[max_ind], axis=0)
                # Remove indexed spots from future use
                spot_mask *= rem_spot_mask
                rem_spot_mask *= ~spot_mask

                # Finally, find the value
                val = np.nansum(pixel_df[sum_key].values[spot_mask])
                spot_matches[max_ind] = 0

                # Fill value
                plot_dict[phase_list[max_ind].name][indices] = val

        elif method in ['minimize_q_error']:
        # Minimize Q difference
        # Should work better for perfect crystals and detector calibration...
            stacked_diffs = np.stack([np.min(diffs, axis=0) for diffs in phase_diffs])
            spot_mask = np.min(stacked_diffs, axis=0) < near_thresh
            phase_ind = np.argmin(stacked_diffs, axis=0)
            phase_ind[~spot_mask] = -1
            for i in range(len(phase_list)):
                val = np.nansum(pixel_df[sum_key].values[phase_ind == i])
                plot_dict[phase_list[i].name][indices] = val
            rem_spot_mask = ~spot_mask

        # Collect unmatched spots
        if np.any(rem_spot_mask):
            val = np.nansum(pixel_df[sum_key].values[rem_spot_mask])
            plot_dict['unmatched'][indices] = val


  0%|          | 0/3321 [00:00<?, ?it/s]

100%|██████████| 3321/3321 [00:02<00:00, 1577.30it/s]


In [48]:
fig, axes = plt.subplots(2, 2, figsize=(10, 5), dpi=200)
ax = axes.ravel()

for i, key in enumerate(plot_dict.keys()):
    if key == 'unmatched':
        pass
        continue

    im = ax[i].imshow(plot_dict[key], extent=test.map_extent())
    fig.colorbar(im, ax=ax[i], shrink=0.4)

    ax[i].set_title(key)

plt.tight_layout()

In [16]:
from orix.crystal_map import CrystalMap
from orix.quaternion import Rotation as orix_Rotation
from orix.quaternion import Orientation as orix_Orientation
from orix.crystal_map.phase_list import Phase as orix_Phase
from orix.crystal_map.phase_list import PhaseList

In [401]:
orientation_map = np.empty((*test.map.map_shape, 3, 3))

for index in range(test.map.num_images):
    indices = np.unravel_index(index, test.map.map_shape)
    
    if np.any(np.isnan(euler_map[indices])):
        orientation_map[indices] = np.nan
    else:
        orientation_map[indices] = Rotation.from_euler('zxz', euler_map[indices], degrees=True).as_matrix()

In [35]:
o_r = orix_Rotation.from_matrix(orientation_map.reshape(-1, 3, 3))

In [36]:
phase_id = []
x_list = []
y_list = []

for index in range(test.map.num_images):
    indices = np.unravel_index(index, test.map.map_shape)

    if np.any(np.isnan(orientation_map[indices])):
        phase_id.append(-1)
    else:
        phase_id.append(0)

    x_list.append(test.pos_dict['map_x'][indices])
    y_list.append(test.pos_dict['map_y'][indices])

In [62]:
cif_dir = '''C:\\Users\\emusterma\\OneDrive - Brookhaven National Laboratory\\Documents\\Postdoc\\Literature\\CIF\\'''
#test.clear_phases()
#test.load_phase('AMCSD\\Stibnite_0008636.cif', filedir=cif_dir, phase_name="stibnite")
##test.load_phase('Unknown\\LiNbO3.cif', filedir=cif_dir, phase_name="LiNbO3 new")
#test.load_phase('Barker\\1521772COD.cif', filedir=cif_dir, phase_name="liNbO3 old")
#test.load_phase('Barker\\LiNbO3.cif', filedir=cif_dir, phase_name="LiNbO3 148")

orix_phase = orix_Phase.from_cif(f'{cif_dir}AMCSD\\Stibnite_0008636.cif')
orix_phase.name = 'stibnite'
orix_phase = orix_Phase.from_cif(f'{cif_dir}Unknown\\LiNbO3.cif')
#orix_phase = orix_Phase.from_cif(f'{cif_dir}Barker\\1521772COD.cif')
#orix_phase = orix_Phase.from_cif(f'{cif_dir}Barker\\LiNbO3.cif')
orix_phase.name = 'linbo3'

In [63]:
x = np.linspace(*test.map_extent()[:2], test.map.map_shape[1])
y = np.linspace(*test.map_extent()[2:], test.map.map_shape[0])

#x = range(test.map.map_shape[1])
#y = range(test.map.map_shape[0])

xx, yy = np.meshgrid(x, y)
xx -= np.min(xx)
yy -= np.min(yy)

crystalmap = CrystalMap(rotations=o_r, phase_id=np.array(phase_id), x=xx.ravel(), y=yy.ravel(), phase_list=PhaseList(orix_phase))

In [64]:
from orix import plot
from orix.vector import Vector3d

pg_laue = crystalmap.phases[0].point_group.laue
o_sb = crystalmap['linbo3'].orientations

ipf_key = plot.IPFColorKeyTSL(pg_laue, direction=Vector3d([0, 0, 1]))
rgb_au = ipf_key.orientation2color(o_sb)

In [65]:
pg_laue

Symmetry (12,) -3m
[[ 1.     0.     0.     0.   ]
 [ 0.5    0.     0.     0.866]
 [-0.5    0.     0.     0.866]
 [ 0.     1.     0.     0.   ]
 [ 0.     0.5    0.866  0.   ]
 [ 0.    -0.5    0.866  0.   ]
 [ 1.     0.     0.     0.   ]
 [ 0.5    0.     0.     0.866]
 [-0.5    0.     0.     0.866]
 [ 0.     1.     0.     0.   ]
 [ 0.     0.5    0.866  0.   ]
 [ 0.    -0.5    0.866  0.   ]]

In [52]:
crystalmap['linbo3'].plot(rgb_au)

In [201]:
I = np.eye(3)

ref_ori = orix_Orientation.from_matrix(I)
x_ori = crystalmap[40, 30].orientations

In [215]:
ref_ori.angle_with_outer(x_ori, degrees=True)

array([[79.56828524]])

In [240]:
x_ori

Orientation (1,) mmm
[[0.103  0.7685 0.6087 0.1686]]

In [241]:
x_ori.map_into_symmetry_reduced_zone(verbose=True)

 25%|██▌       | 2/8 [00:00<00:00, 76.01it/s]


Orientation (1,) mmm
[[-0.7685  0.103   0.1686 -0.6087]]

In [299]:
from orix.quaternion import OrientationRegion

Gl, Gr = x_ori._symmetry
symmetry_pairs = list(product(Gl, Gr))

all_ori = []
orientation_region = OrientationRegion.from_symmetry(Gl, Gr)
o_inside = x_ori.__class__.identity(x_ori.shape)
outside = np.ones(x_ori.shape, dtype=bool)
for gl, gr in symmetry_pairs:
    o_transformed = gl * x_ori[outside] * gr
    all_ori.append(gl * x_ori * gr)
    o_inside[outside] = o_transformed
    outside = ~(o_inside < orientation_region)
    #if not np.any(outside):
    #    break'''
o_inside._symmetry = (Gl, Gr)

In [304]:
x_ori.__class__.identity(x_ori.shape)

Orientation (1,) 1
[[1. 0. 0. 0.]]

In [298]:
all_ori[0]

Symmetry (1,) 
[[0.103  0.7685 0.6087 0.1686]]

In [301]:
[ori._symmetry.as_matrix for ori in all_ori]

AttributeError: 'Symmetry' object has no attribute '_symmetry'

In [273]:
outside

array([ True])

In [254]:
Gr

Symmetry (8,) mmm
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  0.  1.]
 [-1.  0.  0.  0.]]

In [252]:
len(symmetry_pairs)

8

In [228]:
from orix.quaternion.orientation import _get_unique_symmetry_elements

symmetry = _get_unique_symmetry_elements(x_ori.symmetry, ref_ori.symmetry)
misorientation = ref_ori * ~x_ori
all_dot_products = Rotation(misorientation).dot_outer(symmetry)

ValueError: setting an array element with a sequence.

In [206]:
ref_ori.unit.dot(crystalmap[40, 30].orientations.unit)

array([0.76846065])

In [205]:
ref_ori.angle_with_outer(crystalmap[40, 30].orientations, degrees=True)

array([[79.56828524]])

In [197]:
crystalmap[40, 30].orientations

Orientation (1,) mmm
[[0.103  0.7685 0.6087 0.1686]]

In [103]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

ax.imshow(rgb_au.reshape(test.map.map_shape))

plt.show()

ValueError: cannot reshape array of size 1572 into shape (81,41)

In [86]:
len(phase_id)

3321

In [88]:
crystalmap.plot('dp')

AttributeError: 'CrystalMap' object has no attribute 'dp'