In [83]:
import os
import matplotlib.pyplot as plt
import numpy as np
#from tqdm.auto import tqdm
from tqdm import tqdm
plt.ioff();
try:
    maindir
except NameError:
    maindir = os.path.dirname(os.getcwd())
for module in tqdm(os.listdir(maindir + '\\testing_modules')):
    %run -i "{maindir}\\testing_modules\\{module}"
base = os.path.dirname(os.path.dirname(maindir)) + '\\'
plt.ion();
np.set_printoptions(suppress=True)
plt.close('All')
%matplotlib qt

100%|██████████| 22/22 [00:00<00:00, 152.47it/s]


In [2]:
import skimage.io as io
import xarray as xr
from collections import OrderedDict
import dask
from tqdm.dask import TqdmCallback
from sklearn.metrics.pairwise import euclidean_distances

In [ ]:
scanid = 149248
filedir = '''C:\\Users\\emusterma\\OneDrive - Brookhaven National Laboratory\\Documents\\Postdoc\\Data\\Condensed Datasets\\'''
map_filename = f'scan{scanid}_dexela_xrd.tif'
h5_filename = f'scan{scanid}_xrd.h5'

try:
    test = XRDMap.from_h5(h5_filename, wd=filedir)
except:
    test = XRDMap.from_image_stack(map_filename, wd=filedir, energy=15, scanid=scanid)
    test.set_calibration('scan149256_dexela_calibration.poni')

In [19]:
scanid = 149235
filedir = '''D:\\Musterman_postdoc\\20231030_Musterman\\'''
map_filename = f'scan{scanid}_dexela_xrd.tif'
h5_filename = f'scan{scanid}_xrd.h5'

try:
    test = XRDMap.from_h5(h5_filename, wd=filedir)
except:
    test = XRDMap.from_image_stack(map_filename, wd=filedir, energy=15, scanid=scanid)
    test.set_calibration('scan149256_dexela.poni')

Loading data from h5 file...
Loading images...done!


In [84]:
scanid = 149566
filedir = '''C:\\Users\\emusterma\\OneDrive - Brookhaven National Laboratory\\Documents\\Postdoc\\Data\\Condensed Datasets\\'''
map_filename = f'scan{scanid}_dexela_xrd.tif'
h5_filename = f'scan{scanid}_xrd.h5'

try:
    test = XRDMap.from_h5(h5_filename, wd=filedir)
except:
    test = XRDMap.from_image_stack(map_filename, wd=filedir, energy=15, scanid=scanid)
    test.set_calibration('scan149562_dexela_calibration.poni')

Loading data from h5 file...
Loading most recent images (background_corrected)...done!
Loading reciprocal positions...done!
Loading reflection spots...done!
XRD Map loaded!


In [70]:
dark_dir = '''C:\\Users\\emusterma\\OneDrive - Brookhaven National Laboratory\\Documents\\Postdoc\\Data\\Condensed Datasets\\'''
dark_field = io.imread(f'{dark_dir}dexela_df_avg.tif')
scaled_df = dark_field * np.median(test.map.min_image) / np.median(dark_field)
test.map.correct_dark_field(dark_field=scaled_df)
test.map.correct_outliers()

# Much faster for smaller images. Should not matter when this is applied...
test.map.normalize_scaler()

Correcting dark-field...done!
Finding and correcting image outliers...

  0%|          | 0/36 [00:00<?, ?it/s]

100%|██████████| 36/36 [00:00<00:00, 61.41it/s]


done!
No scaler array given. Approximating with image medians...
Normalize image scalers...done!


In [17]:
data.shape

(6, 6, 486, 768)

In [22]:
data.compute().ndim

4

In [28]:
image = data.compute()[0, 0]

In [30]:
np.all(image == median_filter(image, size=1))

True

In [40]:
([1,]*data.ndim)

[1, 1, 1, 1]

In [85]:
significance = None
tolerance = 3
size = 2

data = test.map.images.copy()

size_iter = np.ones(data.ndim, dtype=np.int8)
size_iter[-2:] = size, size

med_image = median_filter(data, size=size_iter)

ratio_image = np.abs(data / med_image)
diff_image = np.abs(data - med_image)

if significance is None:
    significance = 5 * np.std(data)

replace_mask = (ratio_image > tolerance) & (diff_image > significance)

for index in zip(*np.where(replace_mask.compute())):
    data[index] = med_image[index]

data_replaced = 

#data[replace_mask] = med_image[replace_mask]

c:\Users\emusterma\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask\core.py:127: RuntimeWarning: divide by zero encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
c:\Users\emusterma\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask\core.py:127: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))


In [90]:
np.sum(replace_mask).compute()

c:\Users\emusterma\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask\core.py:127: RuntimeWarning: divide by zero encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
c:\Users\emusterma\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask\core.py:127: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))


34

In [52]:
replace_mask.shape

(6, 6, 486, 768)

In [58]:
print(data[replace_mask].shape)
print(med_image[replace_mask].shape)

(nan,)
(45,)


In [61]:
data[replace_mask].compute() = med_image[replace_mask]

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (2656411176.py, line 1)

In [66]:
for index in zip(*np.where(replace_mask.compute())):
    data[index] = med_image[index]

In [63]:
np.where(replace_mask.compute())

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5,
        5], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 4, 4, 4, 5, 5,
        5, 0, 1, 2, 3, 4, 4, 4, 5, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 2, 3, 4,
        5], dtype=int64),
 array([242, 242, 242, 242, 242, 242, 242, 242, 242, 242, 242, 242, 242,
        242, 242, 242, 167, 188, 242, 364, 191, 242, 474, 242, 242, 242,
        242, 159, 160, 242, 242, 423, 242, 242, 242, 242, 242, 242, 242,
        242, 242, 471, 242, 242, 242], dtype=int64),
 array([605, 605, 605, 605, 605, 605, 605, 605, 605, 605, 605, 605, 605,
        605, 605, 605, 170,  11, 605, 352, 279, 605,  92, 605, 605, 605,
        605, 422, 420, 605, 605, 210, 605, 605, 605, 605, 605, 605, 605,
        605, 605, 117, 605, 605, 605], dtype=int64))

In [71]:
test.map.apply_lorentz_correction(ai=test.ai)
test.map.apply_polarization_correction(ai=test.ai)
test.map.apply_solidangle_correction(ai=test.ai)

Applying Lorentz correction...

done!
Applying X-ray polarization correction...done!
Applying solid angle correction...done!


In [72]:
test.map.apply_defect_mask(min_bounds=(-5, 0.5), max_bounds=(0, np.inf))
test.map.estimate_background(method='bruckner')
#test.map.estimate_background(method='gaussian', sigma=50)
test.map.remove_background()
test.map.apply_defect_mask(min_bounds=(-5, 0), max_bounds=(0, np.inf))

Estimating background with Bruckner algorithm.


  0%|          | 0/36 [00:00<?, ?it/s]

100%|██████████| 36/36 [00:00<00:00, 36.35it/s]

Removing background...done!


In [36]:
cif_dir = '''C:\\Users\\emusterma\\OneDrive - Brookhaven National Laboratory\\Documents\\Postdoc\\Literature\\CIF\\'''
test.clear_phases()
for filename, phase_name in zip(['AMCSD\\Hematite_0017806.cif',
                                 'AMCSD\\Iron-alpha_0011214.cif',
                                 'AMCSD\\Iron-beta_0011215.cif',
                                 'AMCSD\\Iron-delta_0011216.cif',
                                 'AMCSD\\Iron_0011146.cif',
                                 'AMCSD\\Cementite_0013523.cif',
                                 'AMCSD\\Zincite_0011555.cif'],
                                ['Hematite', 'Iron-ferrite', 'Iron-beta',
                                 'Iron-delta', 'Iron-austenite', 'Cementite',
                                 'Zincite']):
    
    test.load_phase(filename, filedir=cif_dir, phase_name=phase_name)

In [41]:
cif_dir = '''C:\\Users\\emusterma\\OneDrive - Brookhaven National Laboratory\\Documents\\Postdoc\\Literature\\CIF\\'''
test.clear_phases()
test.load_phase('Barker\\1521772COD.cif', filedir=cif_dir, phase_name="LiNbO3 161")
test.load_phase('Barker\\LiNbO3.cif', filedir=cif_dir, phase_name="LiNbO3 148")
test.load_phase('AMCSD\\Platinum_0011157.cif', filedir=cif_dir, phase_name="Platinum")
test.load_phase('AMCSD\\Calcite_0000984.cif', filedir=cif_dir, phase_name="Calcite")
#test.load_phase('AMCSD\\Aluminum_0011136.cif', filedir=cif_dir, phase_name="Aluminum")
test.load_phase('AMCSD\\Zincite_0011555.cif', filedir=cif_dir, phase_name="Zincite")
#test.load_phase('AMCSD\\Gold_0011140.cif', filedir=cif_dir, phase_name="Gold")
#test.load_phase('AMCSD\\Chromium_0011209.cif', filedir=cif_dir, phase_name="Chromium BCC")
#test.load_phase('AMCSD\\Chromium_0011170.cif', filedir=cif_dir, phase_name="Chromium HCP")
#test.load_phase('AMCSD\\Chromium_0011144.cif', filedir=cif_dir, phase_name="Chromium FCC")

XU.materials: Warning: element O used instead of O-2
XU.materials: Warning: element Nb used instead of Nb+5
XU.materials: Warning: element Li used instead of Li+1


In [37]:
test.select_phases(remove_less_than=0.1)

In [38]:
test.map.interactive_map()

In [17]:
test.calibrate_images()
test.map.apply_defect_mask(min_bounds=(-5, 0.05), max_bounds=(0, np.inf))
test.map.rescale_images(arr_min=0)

Composite of current images is not saved. Creating composite.
Calibrating images...

100%|██████████| 36/36 [00:08<00:00,  4.43it/s]

done!
Writing reciprocal positions...done!
Acquring and writing calibration mask...

done!


In [73]:
test.map.apply_defect_mask(min_bounds=(-5, 0.25), max_bounds=(-0.1, np.inf))
test.map.rescale_images(arr_min=0)
test.map.save_images()

In [74]:
test.plot_interactive_map(img_vmin=0, img_vmax=1)

In [92]:
image = np.copy(test.map.images[0, 0])
image[~test.map.mask] = 0
test.plot_image(image)

In [59]:
i = np.random.randint(test.map.map_shape[0])
j = np.random.randint(test.map.map_shape[1])
#i, j = 2, 5
#i, j = 1, 0
#i, j = 3, 4
#i, j = 5, 0
#i, j = 3, 2
i, j = 4, 2

#out = spot_search(test.map.images[i, j], bkg_noise=map_noise, multiplier=3, plotme=True, mask=test.map.mask, expansion=0, sigma=3)
out = spot_search(test.map.images[i, j], multiplier=15, plotme=True, mask=test.map.mask, expansion=10, size=1)

In [196]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

ax.plot(np.sum(test.map.images[5, 0], axis=0))

plt.show()

In [586]:
test.plot_image([3, 4], spots=True)

In [112]:
test.plot_image([0, 0])

In [75]:
#test.map.images = rescale_array(test.map.images, lower=0, upper=100)
test.find_spots(multiplier=15, expansion=10, radius=10, size=1)

Estimating spot characteristics...: 100%|██████████| 2888/2888 [00:09<00:00, 304.08it/s]


In [76]:
test.fit_spots(GaussianFunctions, max_dist=0.1, sigma=1)

Scheduling blob segmentation for spot fits...:   0%|          | 0/36 [00:00<?, ?it/s]

Fitting spots in blobs...: 100%|██████████| 2505/2505 [01:11<00:00, 35.10it/s]

Successfully fit 2885 / 2888 spots ( 99.9 % ).


In [77]:
test.initial_spot_analysis()

Extracting more information from peak paramters...


Iterating through spots...: 100%|██████████| 2888/2888 [00:01<00:00, 2118.10it/s]

done!
Converting peaks positions to q-space...done!


In [78]:
test.spots.loc[100]

map_x               2.000000
map_y               1.000000
guess_height        0.586651
guess_img_x       233.000000
guess_img_y       764.000000
guess_tth          41.099325
guess_chi          -0.895150
guess_cen_tth      41.134554
guess_cen_chi      -0.952739
guess_fwhm_tth      0.248874
guess_fwhm_chi      0.643375
guess_int          26.464703
fit_amp             0.490008
fit_tth0           41.158458
fit_chi0           -0.961275
fit_fwhm_tth        0.198646
fit_fwhm_chi        0.757044
fit_theta           2.916152
fit_offset         -0.001760
fit_r_squared       0.928892
fit_integrated      0.083497
fit_fwhm_a          0.236903
fit_fwhm_b          0.745957
qx                 -5.002239
qy                 -0.083933
qz                 -1.878413
Name: 100, dtype: float64

In [114]:
test.map.corrections

{'dark_field': True,
 'flat_field': False,
 'outliers': True,
 'pixel_defects': True,
 'pixel_distortions': False,
 'polar_calibration': False,
 'solid_angle': True,
 'polarization': True,
 'lorentz': True,
 'scaler_intensity': True,
 'background': True}

In [82]:
test.plot_image(spots=True)

In [90]:
plot_map = np.zeros(test.map.map_shape)
plot_map[:] = np.nan

for image_index in range(test.map.num_images):
    indices = np.unravel_index(image_index, test.map.map_shape)
    pixel_df = test.spots[(test.spots['map_x'] == indices[0])
                          & (test.spots['map_y'] == indices[1])]
    
    if len(pixel_df) < 1:
        plot_map[indices] = 0
    else:
        #plot_map[indices] = np.sum(pixel_df['guess_int'])
        #plot_map[indices] = np.sum(pixel_df['fit_amp'])
        #plot_map[indices] = np.sum(pixel_df['fit_integrated'])
        #plot_map[indices] = np.mean(pixel_df['fit_tth0'])
        #plot_map[indices] = len(pixel_df)
        #plot_map[indices] = np.nanmedian(pixel_df['qz'])
        #plot_map[indices] = np.nanmin(pixel_df['fit_r_squared'])
        plot_map[indices] = pixel_df.iloc[np.argmax(pixel_df['fit_integrated'])]['fit_tth0']
        plot_map[indices] = pixel_df.iloc[np.argmax(pixel_df['fit_integrated'])]['fit_chi0']


fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

im = ax.imshow(plot_map)
fig.colorbar(im, ax=ax)
ax.set_title('Spot Value')

plt.show()

In [112]:
test.plot_interactive_map(display_map=plot_map, img_vmin=0, img_vmax=1)

In [51]:
test.plot_image([0, 2], spots=True)

In [77]:
test.plot_reconstruction([0, 2], plot_residual=True)

In [45]:
pixel_df = test.spots[(test.spots['map_x'] == 3)
                        & (test.spots['map_y'] == 3)]

In [47]:
pixel_df.iloc[0]

map_x               3.000000
map_y               3.000000
guess_height        5.275062
guess_img_x        30.000000
guess_img_y       678.000000
guess_tth          38.512360
guess_chi         -13.624387
guess_cen_tth      38.505309
guess_cen_chi     -13.599907
guess_fwhm_tth      0.426384
guess_fwhm_chi      0.687899
guess_int         101.430588
fit_amp             4.920459
fit_tth0           38.504399
fit_chi0          -13.640256
fit_fwhm_tth        0.126779
fit_fwhm_chi        0.169940
fit_theta           6.327112
fit_offset          0.138128
fit_r_squared       0.859608
fit_integrated      0.120120
fit_fwhm_a          0.144735
fit_fwhm_b          0.154934
qx                 -4.599082
qy                 -1.116056
qz                 -1.652888
Name: 51, dtype: float64

In [40]:
test.plot_image(test.map.spot_masks[3, 3])

In [104]:
test.plot_image(test.map.med_image)

In [110]:
test.plot_q_space(pixel_indices=[1, 3])

KeyError: "None of [Index(['qx', 'qy', 'qz'], dtype='object')] are in the [index]"

In [111]:
pixel_indices=[1, 3]

pixel_df = test.spots[(test.spots['map_x'] == pixel_indices[0])
                        & (test.spots['map_y'] == pixel_indices[1])].copy()

In [94]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

ax.scatter(test.spots['guess_cen_chi'], test.spots['fit_chi0'], s=1, c='k', alpha=0.5)

plt.show()

In [98]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

image = test.map.composite_image

#tth = test.tth
intensity = np.sum(test.map.composite_image, axis=0)
#pixels = np.sum(test.map.calibration_mask, axis=0)

x, bins, _ = ax.hist(test.spots['guess_cen_tth'].values, bins=2000, weights=test.spots['guess_height'].values, label='spot center', density=True)
#ax.plot(tth, rescale_array(intensity / pixels, lower=np.min(x), upper=np.max(x)), label='integrated intensity')
ax.legend()

plt.show()

In [101]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

image = test.map.composite_image

#tth = test.tth
#intensity = np.sum(test.map.composite_image, axis=0)
#pixels = np.sum(test.map.calibration_mask, axis=0)

x, bins, _ = ax.hist(test.spots['fit_tth0'].values, bins=2500, label='spot center', density=True)
#ax.plot(tth, rescale_array(intensity / pixels, lower=np.min(x), upper=np.max(x)), label='integrated intensity')
ax.legend()

plt.show()

In [103]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

x, bins, _ = ax.hist(test.spots['fit_fwhm_tth'].values, bins=50, label='spot center', density=True)
ax.legend()

plt.show()

In [104]:
test.plot_image(test.ai.position_array()[:, :, 2])

In [85]:
x_coords, y_coords = np.meshgrid(test.tth, test.chi[::-1])
q = q_vect(x_coords, y_coords, wavelength=test.wavelength)

pixel_df = test.spots[(test.spots['map_x'] == 1)
                        & (test.spots['map_y'] == 0)].copy()

In [135]:
q = q_vect(test.ai.twoThetaArray(), test.ai.chiArray(), wavelength=test.wavelength, radians=True)

In [55]:
np.tile(np.array([0, 0, 1]), tth.shape).shape

(486, 2304)

In [99]:
a = np.array([0, 0, 1])
b = np.full((486, 768, 3), a)

In [20]:
np.asarray([[0, 0, 1],] * len(test.tth)).T.shape

(3, 1483)

In [123]:
# Q-space plotting

skip = 500

x_coords, y_coords = np.meshgrid(test.tth, test.chi[::-1])
q = q_vect(x_coords, y_coords, wavelength=test.wavelength)

pixel_df = test.spots[(test.spots['map_x'] == 1)
                        & (test.spots['map_y'] == 0)].copy()


fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200, subplot_kw={'projection':'3d'})

# Plot sampled Ewald sphere
#ax.scatter(q[0].ravel()[::skip], q[1].ravel()[::skip], q[2].ravel()[::skip], s=1, c='k', alpha=0.2)
q_mask = q[:, test.map.mask]
ax.plot_trisurf(q_mask[0].ravel()[::skip],
                q_mask[1].ravel()[::skip],
                q_mask[2].ravel()[::skip],
                alpha=0.5, label='detector')


# Plot full Ewald sphere
u = np.linspace(0, 2 * np.pi, 100)
v = np.linspace(0, np.pi, 100)
radius = 2 * np.pi / test.wavelength
x =  radius * np.outer(np.cos(u), np.sin(v))
y = radius * np.outer(np.sin(u), np.sin(v))
z = radius * np.outer(np.ones(np.size(u)), np.cos(v))
ax.plot_surface(x, y, z - radius, alpha=0.2, color='k', label='Ewald sphere')

ax.scatter(*test.spots.loc[0:1000, ['qx', 'qy', 'qz']].values.T, s=1, c='r', label='spots')
#ax.scatter(*pixel_df[['qx', 'qy', 'qz']].values.T, s=1, c='r', label='spots')

# Sample geometry
ax.quiver([0, 0], [0, 0], [-2 * radius, -radius], [0, 0], [0, 0], [radius, radius], colors='k')
ax.scatter(0, 0, 0, marker='o', s=10, facecolors='none', edgecolors='k', label='transmission')
ax.scatter(0, 0, -radius, marker='h', s=10, c='b', label='sample')

# Detector extent
#corner_indices = np.array([[0, 0], [-1, 0], [0, -1], [-1, -1]]).T
#q_corn = q[:, *corner_indices]
#ax.quiver([0,] * 4,
#          [0,] * 4,
#          [-radius,] * 4,
#          q_corn[0],
#          q_corn[1],
#          q_corn[2] + radius, colors='gray', lw=0.5)


ax.set_xlabel('qx [Å⁻¹]')
ax.set_ylabel('qy [Å⁻¹]')
ax.set_zlabel('qz [Å⁻¹]')
ax.set_aspect('equal')

# Initial view
ax.view_init(elev=-45, azim=90, roll=0)
plt.show()

In [226]:
tth_arr = test.ai.twoThetaArray()
chi_arr = test.ai.chiArray()

polar_correction = test.ai.polarization(factor=0.9)
solidangle_correction = test.ai.solidAngleArray()
lorentz_correction = 1 / (np.sin(tth_arr / 2) * np.sin(tth_arr))

In [240]:
tth_num = 1500
chi_num = 1500

blank_image = np.ones(test.map.image_shape)

pyfai_correction = test.integrate_2d(blank_image, tth_num, chi_num, polarization_factor=0.9, correctSolidAngle=True)[0]

corrected_image = blank_image / solidangle_correction / polar_correction

self_correction = test.integrate_2d(corrected_image, tth_num, chi_num, polarization_factor=None, correctSolidAngle=False)[0]

In [234]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

im = ax.imshow(self_correction)
fig.colorbar(im, ax=ax)

plt.show()

In [239]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)
residual = pyfai_correction - self_correction
ext = np.max(np.abs(residual))

im = ax.imshow(residual, cmap='bwr', vmin=-ext, vmax=ext)
fig.colorbar(im, ax=ax)

plt.show()

In [235]:
pyfai_correction - self_correction

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [111]:
# Real-space plotting

skip = 300

fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200, subplot_kw={'projection':'3d'})

# Plot detector position
xyz = test.ai.position_array()

xyz[:, :, 0] *= -1 # Transform to synchrotron standard. Not sure if correct

x = xyz[:, :, 0].ravel()[::skip]
y = xyz[:, :, 1].ravel()[::skip]
z = xyz[:, :, 2].ravel()[::skip]


ax.plot_trisurf(x, y, z,
                alpha=0.5, label='detector')

# X-ray beam
radius = test.ai.dist
ax.quiver([0], [0], [-radius], [0], [0], [radius], colors='k')
ax.scatter(0, 0, 0, marker='h', s=10, c='b', label='sample')

# Detector
corner_indices = np.array([[0, 0], [-1, 0], [0, -1], [-1, -1]]).T
corn = xyz[*corner_indices].T
ax.quiver([0,] * 4,
          [0,] * 4,
          [0,] * 4,
          corn[0],
          corn[1],
          corn[2], colors='gray', lw=0.5)

ax.set_xlabel('x [m]')
ax.set_ylabel('y [m]')
ax.set_zlabel('z [m]')
ax.set_aspect('equal')

# Initial view
ax.view_init(elev=-60, azim=90, roll=0)
plt.show()

In [363]:
radius

7.6015960742345925

In [143]:
pixel_df[['qx', 'qy', 'qz']]

qx        qy        qz
11 -3.236871 -0.327674 -0.731403
10 -2.544562  0.992806 -0.507669
9  -4.712897 -0.427081 -1.652607

In [145]:
pixel_df.iloc[0][['qx', 'qy', 'qz']].values

array([-3.23687107, -0.32767447, -0.73140263])

In [188]:
q_diff = pixel_df.iloc[1][['qx', 'qy', 'qz']].values - pixel_df.iloc[2][['qx', 'qy', 'qz']].values
print(q_diff)

[2.16833467 1.41988698 1.14493823]


In [207]:
q_diff = pixel_df.iloc[0][['qx', 'qy', 'qz']].values - pixel_df.iloc[2][['qx', 'qy', 'qz']].values
print(q_diff)

[1.47602556 0.09940648 0.92120445]


In [214]:
q_diff[0] / test.phases['LiNbO3 161'].a * 2 * np.pi

1.805080408270403

In [208]:
hkl_diff = test.phases['LiNbO3 161'].HKL(q_diff)
print(hkl_diff)

[1.00461135 0.0812853  1.97910167]


In [191]:
hkl_appr = np.round(hkl_diff / np.min(np.abs(hkl_diff))).astype(int)
print(hkl_appr)

[  1 -15  -7]


In [192]:
test.phases['LiNbO3 161'].lattice.equivalent_hkls(hkl_appr)

{(-15, 14, -7),
 (-14, 15, -7),
 (-1, -14, -7),
 (1, -15, -7),
 (14, 1, -7),
 (15, -1, -7)}

In [197]:
test.phases['LiNbO3 161'].lattice.equivalent_hkls([1, 0, 4])

{(-1, 1, 4), (0, -1, 4), (1, 0, 4)}

In [201]:
def vector_angle(V1, V2, radians=False):

    unit_V1 = V1 / np.linalg.norm(V1)
    unit_V2 = V2 / np.linalg.norm(V2)

    theta = np.arccos(np.dot(unit_V1, unit_V2))

    return np.degrees(theta)

In [204]:
vector_angle(pixel_df.iloc[0][['qx', 'qy', 'qz']].values, pixel_df.iloc[2][['qx', 'qy', 'qz']].values)

6.605844468976728

In [262]:
np.linalg.norm(test.phases['LiNbO3 161'].Q([0, 1, 0]))

1.4121214249166707

In [254]:
q1 = q_vect(90, 0, wavelength=2 * np.pi).T[0]
q2 = q_vect(90, 90, wavelength=2 * np.pi).T[0]

In [255]:
np.round(vector_angle(q1, q2) * 2 , 3)

120.0

In [216]:
pixel_df.iloc[0][['qx', 'qy', 'qz']].values

array([-3.23687107, -0.32767447, -0.73140263])

In [215]:
pixel_df.iloc[2][['qx', 'qy', 'qz']].values

array([-4.71289663, -0.42708095, -1.65260708])

In [205]:
test.map.plot_image(test.map.images[1, 0])

In [25]:
pixel_df[['fit_x0']]

fit_x0
11  25.340128
10  21.058268
9   38.500994

In [198]:
test.phases['LiNbO3 161'].reflections['q']

array([1.69136665, 2.33679777, 2.44586605, 2.79279574, 2.81641399,
       2.97371517, 3.3827333 , 3.71240741, 3.76500558, 3.85035617,
       3.982491  , 4.1743437 , 4.23636427, 4.40171243, 4.67359554,
       4.85093845, 4.8641487 , 4.89173211, 4.95730549, 5.07409995,
       5.08713771, 5.11270853, 5.17588294, 5.27491764, 5.42122374,
       5.44446539])

In [196]:
test.phases['LiNbO3 161'].reflections['hkl']

array([[ 0,  1,  2],
       [ 1,  0,  4],
       [ 1,  1,  0],
       [ 0,  0,  6],
       [ 1,  1,  3],
       [ 2,  0,  2],
       [ 0,  2,  4],
       [ 1,  1,  6],
       [ 2,  1,  1],
       [ 1,  2,  2],
       [ 0,  1,  8],
       [ 2,  1,  4],
       [ 0,  3,  0],
       [ 1,  2,  5],
       [ 2,  0,  8],
       [ 1,  1,  9],
       [ 1,  0, 10],
       [ 2,  2,  0],
       [ 2,  1,  7],
       [ 0,  3,  6],
       [ 2,  2,  3],
       [ 1,  3,  1],
       [ 3,  1,  2],
       [ 1,  2,  8],
       [ 1,  3,  4],
       [ 0,  2, 10]])

In [66]:
test.phases['LiNbO3 161'].get_hkl_reflections(tth_range=(0, np.max(test.tth)), energy=test.energy*1e3)

TypeError: '>' not supported between instances of 'list' and 'int'

In [78]:
test.phases['LiNbO3 161'].reflections['hkl'][19]

array([0, 3, 6])

In [89]:
pixel_df.iloc[0, columns==['qx', 'qy', 'qz']]

NameError: name 'columns' is not defined

In [80]:
test.phases['LiNbO3 161'].lattice.equivalent_hkls([0, 3, 6])

{(-3, 0, 6), (0, 3, 6), (3, -3, 6)}

In [207]:
import xrayutilities as xu

data = xu.simpack.PowderDiffraction(test.phases['LiNbO3 161'], en=test.energy*1e3, tt_cutoff=45)

In [226]:
linbo.lattice.get_allowed_hkl(qmax=2)

{(-1, 0, 2), (-1, 1, -2), (0, -1, -2), (0, 1, 2), (1, -1, 2), (1, 0, -2)}

In [271]:
all_refl = linbo.lattice.get_allowed_hkl(qmax=tth_2_q(np.max(test.tth), wavelength=energy_2_wavelength(test.energy)))

In [278]:
q_list = np.linalg.norm(linbo.Q(*refl_list), axis=1)
#q_list.sort()

In [310]:
all_refl = linbo.lattice.get_allowed_hkl(qmax=tth_2_q(np.max(test.tth), wavelength=energy_2_wavelength(test.energy)))
all_q = np.linalg.norm(linbo.Q(*all_refl), axis=1)
all_q = np.round(all_q, 10) # Clean up some errors
sort_refl = [x for _, x in sorted(zip(all_q, all_refl))]
all_q.sort()
F_hkl = np.abs(linbo.StructureFactor(sort_refl))
F_hkl = rescale_array(F_hkl, lower=0, upper=100)

In [316]:
ignore_less = 1
wavelength = energy_2_wavelength(test.energy)

all_refl = linbo.lattice.get_allowed_hkl(qmax=tth_2_q(np.max(test.tth), wavelength=wavelength))
all_q = np.linalg.norm(linbo.Q(*all_refl), axis=1)
all_q = np.round(all_q, 10) # Clean up some errors
sort_refl = [x for _, x in sorted(zip(all_q, all_refl))]
all_q.sort()
F_hkl = np.abs(linbo.StructureFactor(sort_refl))
F_hkl = rescale_array(F_hkl, lower=0, upper=100)

hkl_list = []
q_list = []
int_list = []
tth_list = []
d_list = []

for index, norm_int in enumerate(F_hkl):
    if all_q[index] not in q_list:
        hkl_list.append(sort_refl[index]) # Only takes first hkl value
        q_list.append(all_q[index])
        int_list.append(norm_int)
        tth_list.append(q_2_tth(all_q[index], wavelength=wavelength))
        d_list.append(convert_qd(all_q[index]))
    else:
        int_list[-1] += norm_int # Handles multiplicity
        if np.sum(sort_refl[index]) > np.sum(hkl_list[-1]):
            hkl_list[-1] = sort_refl[index] # bias towards positive hkl values

data = {
    'hkl' : np.array(hkl_list)[int_list > ignore_less],
    'q' : np.array(q_list)[int_list > ignore_less],
    'int' : np.array(int_list)[int_list > ignore_less],
    'tth' : np.array(tth_list)[int_list > ignore_less],
    'd' : np.array(d_list)[int_list > ignore_less]
    }

In [320]:
cif_dir = '''C:\\Users\\emusterma\\OneDrive - Brookhaven National Laboratory\\Documents\\Postdoc\\Literature\\CIF\\'''

test.load_phase('Barker\\1521772COD.cif', filedir=cif_dir, phase_name="LiNbO3 161")
test.load_phase('Barker\\1521772COD.cif', filedir=cif_dir, phase_name="LiNbO3 new")

test.phases['LiNbO3 new'].reflections = data

XU.materials: Warning: element O used instead of O-2
XU.materials: Warning: element Nb used instead of Nb+5
XU.materials: Warning: element Li used instead of Li+1
Did not add LiNbO3 161 since it is already in possible phases.
XU.materials: Warning: element O used instead of O-2
XU.materials: Warning: element Nb used instead of Nb+5
XU.materials: Warning: element Li used instead of Li+1


In [321]:
test.select_phases()

In [18]:
pixel_df.dropna(axis=0, inplace=True)
pixel_df.sort_values(by=['fit_integrated'], inplace=True)

In [19]:
q_arr = pixel_df[['qx', 'qy', 'qz']].values

In [20]:
dist = euclidean_distances(q_arr)

In [21]:
dist

array([[0.        , 1.50765296, 1.74274231],
       [1.50765296, 0.        , 2.8334851 ],
       [1.74274231, 2.8334851 , 0.        ]])

In [239]:
def plot_image(xrdmap, image=None, indices=None, title=None,
               mask=None, spots=False, contours=False,
               aspect='auto', vmin=None, 
               return_plot=False,
               **kwargs):
    
    # Check image type
    if image is not None:
        image = np.asarray(image)
        if len(image.shape) == 1 and len(image) == 2:
            indices = tuple(iter(image))
            image = xrdmap.map.images[indices]
        elif len(image.shape) == 2:
            if indices is not None:
                indices = tuple(indices)
        else:
            raise ValueError(f"Incorrect image shape of {image.shape}. Should be two-dimensional.")
    else:
        if indices is not None:
            indices = tuple(indices)
            image = xrdmap.map.images[indices]
        else:
            i = np.random.randint(xrdmap.map.map_shape[0])
            j = np.random.randint(xrdmap.map.map_shape[1])
            indices = (i, j)
            image = xrdmap.map.images[indices]

    # Check for mask
    if mask is not None:
        if mask is True:
            image = image * xrdmap.map.mask
        elif np.asarray(mask).shape == image.shape:
            image = image * mask
        else:
            raise RuntimeError("Error handling mask input.")
        
    # Plot image
    fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)
    # Allow some flexibility for kwarg inputs
    plot_kwargs = {'c' : 'r',
                   'lw' : 0.5,
                   's' : 1}
    for key in plot_kwargs.keys():
        if key in kwargs.keys():
            plot_kwargs[key] = kwargs[key]

    if hasattr(xrdmap.map, 'extent'):
        if vmin == None:
            vmin = 0
        im = ax.imshow(image, extent=xrdmap.extent, vmin=vmin, aspect=aspect, **kwargs)
        ax.set_xlabel('Scattering Angle, 2θ [°]') # Assumes degrees. Need to change...
        ax.set_ylabel('Azimuthal Angle, χ [°]')
    else:
        im = ax.imshow(image, aspect=aspect, **kwargs)
        ax.set_xlabel('X index')
        ax.set_ylabel('Y index')
    fig.colorbar(im, ax=ax) 

    if title is not None:
        ax.set_title(title)
    elif indices is not None:
        ax.set_title(f'Row = {indices[0]}, Col = {indices[1]}')
    elif xrdmap.map.title is not None:
        ax.set_title(xrdmap.map.title)
    else:
        ax.set_title('Input Image')

    if indices is not None:
        # Set some default values

        
        # Plot spots
        if spots and hasattr(xrdmap, 'spots'):
            pixel_df = test.spots[(test.spots['map_x'] == indices[0]) & (test.spots['map_y'] == indices[1])].copy()
            if any([x[:3] == 'fit' for x in pixel_df.keys()]):
                pixel_df.dropna(axis=0, inplace=True)
                spots = pixel_df[['fit_y0', 'fit_x0']].values
            else:
                spots = pixel_df[['guess_ceny', 'guess_cenx']].values
            ax.scatter(spots[:, 1], spots[:, 0], s=plot_kwargs['s'], c=plot_kwargs['c'])
        
        elif spots and not hasattr(xrdmap, 'spots'):
            print('Warning: Plotting spots requested, but xrdmap does not have any spots!')

        # Plot contours
        if contours and hasattr(xrdmap.map, 'spot_masks'):
            blob_img = label(xrdmap.map.spot_masks[indices])
            blob_contours = find_blob_contours(blob_img)
            for i in range(len(blob_contours)):
                blob_contours[i] = estimate_reciprocal_coords(blob_contours[i], image.shape, tth=xrdmap.tth, chi=xrdmap.chi)
            for contour in blob_contours:
                ax.plot(*contour, c=plot_kwargs['c'], lw=plot_kwargs['lw'])
            
        elif contours and not hasattr(xrdmap, 'spot_masks'):
            print('Warning: Plotting spots requested, but xrdmap does not have any spots!')
    
    elif spots or contours:
        print('Warning: Cannot request spots or contours without providing map indices!')

    if return_plot:
        return fig, ax
    
    plt.show()

In [174]:
plot_image(test, test.map.mask)

In [166]:
indices = pixel_df.index

In [172]:
pixel_df.loc[indices[-1], ['guess_height', 'guess_cenx']].values

array([ 0.17024574, 12.70959352])

In [242]:
def reconstruct_image(xrdmap, indices=None, plot_residual=False, **kwargs):
    if not hasattr(xrdmap, 'spots'):
        raise RuntimeError('xrdmap does not have any spots!')

    if indices is None:
        i = np.random.randint(xrdmap.map.map_shape[0])
        j = np.random.randint(xrdmap.map.map_shape[1])
        indices = (i, j)
    else:
        indices = tuple(indices)
    
    if hasattr(xrdmap, 'spot_model'):
        spot_model = xrdmap.spot_model
    spot_model = GaussianFunctions
    
    pixel_df = test.spots[(test.spots['map_x'] == indices[0]) & (test.spots['map_y'] == indices[1])].copy()
    x_coords, y_coords = np.meshgrid(xrdmap.tth, xrdmap.chi[::-1])

    if any([x[:3] == 'fit' for x in pixel_df.keys()]):
        prefix = 'fit'
        pixel_df.dropna(axis=0, inplace=True)
        param_labels = [x for x in test.spots.loc[0].keys() if x[:3] == 'fit'][:6]
    else:
        prefix = 'guess'
        param_labels = ['height', 'cenx', 'ceny', 'stdx', 'stdy']
        param_labels = [f'guess_{param_label}' for param_label in param_labels]
        spot_model = GaussianFunctions

    fit_args = []
    for index in pixel_df.index:
        fit_args.extend(pixel_df.loc[index, param_labels].values)
        if prefix == 'guess':
            fit_args.append(0) # Filling in theta value

    if len(fit_args) > 0:
        #return fit_args
        recon_image = spot_model.multi_2d([x_coords.ravel(), y_coords.ravel()], 0, *fit_args)
        recon_image = recon_image.reshape(xrdmap.map.calibrated_shape)
    else:
        recon_image = np.zeros(xrdmap.map.calibrated_shape)

    if not plot_residual:
        fig, ax = plot_image(xrdmap, recon_image,
                             return_plot=True, indices=indices,
                             **kwargs)
        plt.show()
    else:
        image = xrdmap.map.images[indices]
        residual = recon_image - image
        ext = np.max(np.abs(residual[xrdmap.map.mask]))
        fig, ax = plot_image(xrdmap, residual,
                             title=f'Residual of ({indices[0]}, {indices[1]})',
                             return_plot=True, indices=indices,
                             vmin=-ext, vmax=ext, cmap='bwr', # c='k',
                             **kwargs)
        plt.show()

In [243]:
reconstruct_image(test, [1, 1], plot_residual=True, spots=True)

In [138]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

nan_mask = ~np.isnan(test.spots['fit_integrated'].values)

ax.scatter(test.spots['guess_stdy'].values[nan_mask], test.spots['fit_sigma_y'].values[nan_mask], alpha=0.5, s=1, c='k')

plt.show()

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

nan_mask = ~np.isnan(test.spots['fit_integrated'].values)

ax.scatter(np.array(range(len(test.spots)))[nan_mask], test.spots['guess_height'].values[nan_mask], alpha=0.5, s=1, c='k')

plt.show()

In [ ]:
def iter_rescale_array(arr, lower=0, upper=1, arr_min=None, arr_max=None):
    # Works for arrays of any size including images!
    if arr_min is None:
        arr_min = np.min(arr)
    if arr_max is None:
        arr_max = np.max(arr)
    ext = upper - lower

    @dask.delayed
    def delayed_rescale_array(arr, lower, ext, arr_min, arr_max, indices):
        arr[indices] = lower + ext * ((arr[indices] - arr_min) / (arr_max - arr_min))
        return arr[indices]

    delayed_list = []
    for index in tqdm(range(np.multiply(*arr.shape[:2])), desc='Scheduling...'):
        indices = np.unravel_index(index, arr.shape[:2])

        delayed_list.append(delayed_rescale_array(arr[indices], lower, ext, arr_min, arr_max, indices))

    #return delayed_list
    with TqdmCallback(desc='Computing...', tqdm_class=tqdm):
        dask.compute(*delayed_list)

In [ ]:
test.map.plot_image()

In [ ]:
#nan_med = test.map.med_image
nan_med = median_image
nan_med[~test.map.calibration_mask] = np.nan
ball_bkg = rolling_ball(gaussian_filter(nan_med, sigma=2), radius=50)
ball_bkg[~test.map.calibration_mask] = 0
test.map.remove_background(background=ball_bkg * test.map.calibration_mask)
test.map.images = rescale_array(test.map.images, lower=0, upper=100)

In [ ]:
test.map.update_map_title()
test.map.save_images(units=test.map.calib_unit, labels=['x_ind', 'y_ind', 'chi_ind', 'tth_ind'])

In [ ]:
map_noise = estimate_map_noise(test.map)

In [ ]:
i = np.random.randint(test.map.map_shape[0])
j = np.random.randint(test.map.map_shape[1])

out = spot_search(test.map.images[i, j], bkg_noise=map_noise, multiplier=3, plotme=True)

In [ ]:
test.map.plot_image(out[1] * out[2])

In [ ]:
test.find_spots(multiplier=3)

Characterizing spots...: 100%|██████████| 22193/22193 [09:00<00:00, 41.08it/s]


In [ ]:
test.fit_spots(GaussianFunctions, max_dist=0.75)

Fitting spots in blobs...: 100%|██████████| 19175/19175 [10:19<00:00, 30.95it/s]


Successfully fit 16396 / 22193 spots ( 73.9 % ).


In [ ]:
plot_map = np.zeros(test.map.map_shape)
plot_map[:] = np.nan

for image_index in range(test.map.num_images):
    indices = np.unravel_index(image_index, test.map.map_shape)
    pixel_df = test.spots[(test.spots['map_x'] == indices[0])
                          & (test.spots['map_y'] == indices[1])]
    
    if len(pixel_df) < 1:
        plot_map[indices] = 0
    else:
        plot_map[indices] = np.sum(pixel_df['guess_int'])
        #plot_map[indices] = np.sum(pixel_df['fit_amp'])
        #plot_map[indices] = np.mean(pixel_df['fit_x0'])
        #plot_map[indices] = len(pixel_df)


fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

im = ax.imshow(plot_map)
fig.colorbar(im, ax=ax)
ax.set_title('Spot Value')

plt.show()

In [ ]:
test.map.plot_image()

In [ ]:
[test.phases[phase].get_hkl_reflections(tth_range=(np.min(test.tth), np.max(test.tth))) for phase in test.phases];

pot_tth = np.concatenate([test.phases[key].reflections['tth'] for key in test.phases])
pot_hkl = np.concatenate([test.phases[key].reflections['hkl'] for key in test.phases])
pot_phase = np.concatenate([[key,] * len(test.phases[key].reflections['tth']) for key in test.phases])

search_distance = 0.5 # in degrees
this_phase = 'Iron-ferrite'

plot_map = np.zeros(test.map.map_shape)
plot_map[:] = 0

for image_index in range(test.map.num_images):
    indices = np.unravel_index(image_index, test.map.map_shape)
    pixel_df = test.spots[(test.spots['map_x'] == indices[0])
                          & (test.spots['map_y'] == indices[1])]
    
    if len(pixel_df) < 1:
        plot_map[indices] = 0
    else:
        for spot_index in range(len(pixel_df)):
            min_arr = np.abs(pot_tth - pixel_df.iloc[spot_index]['guess_cenx'])
            #min_arr = np.array([np.abs(x - pot_tth) for x in pixel_df.loc[spot_index, 'fit_x0']])
            min_arr[min_arr > search_distance] = np.nan
            if np.all(np.isnan(min_arr)):
                continue
            #min_index = [np.nanargmin(x) if np.any(~np.isnan(x)) else None for x in min_arr]
            min_index = np.nanargmin(min_arr)

            if pot_phase[min_index] == this_phase:
                plot_map[indices] += pixel_df.iloc[spot_index]['guess_int']

        #plot_map[indices] = np.sum(pixel_df['guess_int'])
        #plot_map[indices] = np.sum(pixel_df['fit_amp'])
        #plot_map[indices] = np.mean(pixel_df['fit_x0'])
        #plot_map[indices] = len(pixel_df)


fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

im = ax.imshow(plot_map)
fig.colorbar(im, ax=ax)
ax.set_title(this_phase)

plt.show()

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

image = test.map.composite_image

tth = test.tth
intensity = np.sum(test.map.composite_image, axis=0)
pixels = np.sum(test.map.calibration_mask, axis=0)

x, bins, _ = ax.hist(test.spots['guess_cenx'].values, bins=2000, weights=test.spots['guess_height'].values, label='spot center', density=True)
ax.plot(tth, rescale_array(intensity / pixels, lower=np.min(x), upper=np.max(x)), label='integrated intensity')
ax.legend()

plt.show()

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

image = test.map.composite_image

tth = test.tth
intensity = np.sum(test.map.composite_image, axis=0)
pixels = np.sum(test.map.calibration_mask, axis=0)

x, bins, _ = ax.hist(test.spots['fit_x0'].values, bins=2500, label='spot center', density=True)
ax.plot(tth, rescale_array(intensity / pixels, lower=np.min(x), upper=np.max(x)), label='integrated intensity')
ax.legend()

plt.show()

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

image = test.map.composite_image

tth = test.tth
x, bins, _ = ax.hist(test.spots['fit_x0'].values, bins=2000, label='fit', range=test.extent[:2], alpha=0.5)
x, bins, _ = ax.hist(test.spots['guess_cenx'].values, bins=2000, label='integrated', range=test.extent[:2], alpha=0.5)

#ax.plot(tth, rescale_array(intensity / pixels, lower=np.min(x), upper=np.max(x)), label='integrated intensity')
ax.legend()

plt.show()

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

image = test.map.composite_image
bins = 2500

guess_val = test.spots['guess_cenx'].values
fit_val = test.spots['fit_x0'].values

tth = test.tth
ext = [np.nanmin([guess_val, fit_val]),
       np.nanmax([guess_val, fit_val])]
x, bins, _ = ax.hist(fit_val, bins=bins, label='fit', alpha=0.5, range=ext)
x, bins, _ = ax.hist(guess_val, bins=bins, label='integrated', alpha=0.5, range=ext)

#ax.plot(tth, rescale_array(intensity / pixels, lower=np.min(x), upper=np.max(x)), label='integrated intensity')
ax.legend()

plt.show()

In [ ]:
thickness = 0.6
corrected_tth = test.tth + (thickness * np.sin(np.radians(test.tth)))
rad = np.radians(corrected_tth / 2)
intensity = np.sum(test.map.composite_image * (np.sin(rad) * np.sin(2 * rad)), axis=0)
intensity = np.sum(test.map.composite_image, axis=0)
pixels = np.sum((test.map.composite_image != 0), axis=0)
phase_vals = phase_selector(intensity / pixels, list(test.phases.values()), corrected_tth)
test.map.images = rescale_array(test.map.images, lower=0, upper=100) # Remove negative values. They break spot stats

In [ ]:
bkg_noise = estimate_map_noise(test)

In [ ]:
i = np.random.randint(test.map.map_shape[0])
j = np.random.randint(test.map.map_shape[1])

out = spot_search(test.map.images[i, j], bkg_noise, multiplier=10, sigma=3, plotme=True)

In [ ]:
test.map.plot_image(test.map.images[i, j] * out[1])

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

bins = 1000
key = 'guess_stdy'
#ax.hist(stat_dict[key], bins=bins, density=True)
ax.hist(stat_dict[key], bins=bins, weights=stat_dict['guess_int'], density=True)

plt.show()

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

image = test.map.composite_image

tth = test.tth
intensity = np.sum(test.map.composite_image, axis=0)
pixels = np.sum(test.map.calibration_mask, axis=0)

x, bins, _ = ax.hist(stat_dict['guess_cenx'], bins=2000, weights=stat_dict['guess_height'], label='spot center', density=True)
ax.plot(tth, rescale_array(intensity / pixels, lower=np.min(x), upper=np.max(x)), label='integrated intensity')
ax.legend()

plt.show()

In [ ]:
stat_df = pd.DataFrame.from_dict(stat_dict)

In [ ]:
plot_map = np.zeros(test.map.map_shape)

for pixel_index in range(test.map.num_images):
    indices = np.unravel_index(pixel_index, test.map.map_shape)
    pixel_df = stat_df.loc[(stat_df['map_x'] == indices[0]) & (stat_df['map_y'] == indices[1])]

    val = np.mean(pixel_df['guess_int'])

    plot_map[indices] = val

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

im = ax.imshow(np.array(plot_map).reshape(test.map.images.shape[:2]))
fig.colorbar(im, ax=ax)
ax.set_title('Total Reflection Intensity')

plt.show()

In [ ]:
[test.phases[phase].get_hkl_reflections() for phase in test.phases];

In [ ]:
new_out = [np.asarray(x) for x in stat_list]

pot_tth = np.concatenate([test.phases[key].reflections['tth'] for key in test.phases])
pot_hkl = np.concatenate([test.phases[key].reflections['hkl'] for key in test.phases])
pot_phase = np.concatenate([[key,] * len(test.phases[key].reflections['tth']) for key in test.phases])

plot_value = []
search_distance = 0.5 # in degrees
phase = 'Iron-austenite'

for spots in new_out:
    if len(spots.shape) > 1:
        #val = np.sum(spots[:, 5])
        min_arr = np.array([np.abs(x - pot_tth) for x in spots[:, 5]])
        min_arr[min_arr > search_distance] = np.nan
        min_index = [np.nanargmin(x) if np.any(~np.isnan(x)) else None for x in min_arr]
        
        val = 0
        for spot_idx, index in enumerate(min_index):
            if index is None:
                continue
            else:
                #raise Exception
                if pot_phase[index] == phase:
                    val += spots[spot_idx, -1]
        
    else:
        val = 0
    
    plot_value.append(val)

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=200)

im = ax.imshow(np.array(plot_value).reshape(test.map.images.shape[:2]))
fig.colorbar(im, ax=ax)
ax.set_title(f'{phase} Total Intensity')

plt.show()

In [ ]:
selected_images = np.median(np.copy(test.map.images[::5, ::5]), axis=(0, 1)) # Randomize for less that certain number of images...
bkg_noise = np.std(selected_images[selected_images != 0])

i = np.random.randint(test.map.images.shape[0])
j = np.random.randint(test.map.images.shape[1])
#i, j = 0, 1
image = test.map.images[i, j]

spot_dict = find_spots(image, bkg_noise,
                               multiplier=10, sigma=3,
                               tth=test.tth, chi=test.chi, plotme=True)
print(len(spot_dict['guess_height']))

In [ ]:
def dask_find_spots(pixel):
    spot_dict, mask = find_spots(pixel, bkg_noise,
                               multiplier=10, sigma=3,
                               tth=test.tth, chi=test.chi)
    return spot_dict, mask

iterable = test.map.images.reshape(test.map.num_images, len(test.chi), len(test.tth))
spot_dict_lst = parallel_loop(dask_find_spots, iterable)

In [ ]:
iterable = test.map.images.reshape(test.map.num_images, len(test.chi), len(test.tth))

spot_dict_lst = []
mask_lst = []
for pixel in iterable:
    spot_dict, mask = find_spots(pixel, bkg_noise,
                               multiplier=10, sigma=3,
                               tth=test.tth, chi=test.chi)
    spot_dict_lst.append(spot_dict)
    mask_lst.append(mask)

In [ ]:
elements_folder = f'output_tiff_scan2D_{scanid}_xs_sum8ch\\'

element_maps = {}
for element in os.listdir(f'{filedir}{elements_folder}'):
    el_im = io.imread(f'{filedir}{elements_folder}{element}')
    element_maps[str(element[:-5])] = el_im

In [ ]:
key = 'detsum_Fe_K'
#interactive_dynamic_2d_plot(proc_map, range(121), range(121), img_vmin=10, img_vmax=100, display_map=element_maps['detsum_Pt_L'], map_vmin=1e4, map_vmax=1.1e4)
interactive_dynamic_2d_plot(test.map.images, range(test.map.images.shape[0]), range(test.map.images.shape[1]), display_map=element_maps[key], display_title=key)